import type {
  KnowledgeBase,
  KnowledgeCategory,
  KnowledgeFile,
  KnowledgeUser,
  ParseException,
  PermissionMember,
  PermissionRequest,
  PersonalDirectory,
  UploadApproval,
  UploadRecord,
} from "./types";

export const CURRENT_KNOWLEDGE_USER: KnowledgeUser = {
  id: "u-run-admin",
  name: "张工",
  departmentId: "dept-run",
  departmentName: "运行部",
  role: "departmentAdmin",
};

export const KNOWLEDGE_DEPARTMENTS = [
  { id: "dept-run", name: "运行部" },
  { id: "dept-tech", name: "技术部" },
  { id: "dept-dispatch", name: "调度部" },
  { id: "dept-maintenance", name: "检修部" },
];

export const KNOWLEDGE_CATEGORIES: KnowledgeCategory[] = [
  { id: "cat-run", name: "运行专业" },
  { id: "cat-run-rules", parentId: "cat-run", name: "规程制度" },
  { id: "cat-run-market", parentId: "cat-run", name: "交易与考核" },
  { id: "cat-dispatch", name: "调度协同" },
  { id: "cat-tech", name: "设备技术" },
  { id: "cat-safety", name: "公共制度" },
];

export const KNOWLEDGE_BASES: KnowledgeBase[] = [
  {
    id: "kb-personal-work",
    name: "运行值班笔记库",
    description: "值班记录、异常处置复盘与班组交接要点",
    scope: "personal",
    personalDirectoryId: "personal-work",
    departmentId: "dept-run",
    departmentName: "运行部",
    fileCount: 5,
    status: "enabled",
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-07 19:10",
    ownerName: "张工",
    isPinned: true,
  },
  {
    id: "kb-personal-study",
    name: "规程学习摘录库",
    description: "并网规程摘录、考核要点与培训复习材料",
    scope: "personal",
    personalDirectoryId: "personal-study",
    departmentId: "dept-run",
    departmentName: "运行部",
    fileCount: 2,
    status: "enabled",
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-05 11:40",
    ownerName: "张工",
  },
  {
    id: "kb-grid-operation",
    name: "并网运行管理库",
    description: "并网运行规程、典型操作票与异常处置经验资料",
    scope: "department",
    categoryId: "cat-run-rules",
    categoryPath: ["运行专业", "规程制度"],
    departmentId: "dept-run",
    departmentName: "运行部",
    fileCount: 16,
    status: "enabled",
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-07-07 09:15",
    ownerName: "运行部",
    isPinned: true,
  },
  {
    id: "kb-agc",
    name: "AGC 考核标准库",
    description: "AGC 考核指标、实施细则与月度统计方法",
    scope: "department",
    categoryId: "cat-run-market",
    categoryPath: ["运行专业", "交易与考核"],
    departmentId: "dept-run",
    departmentName: "运行部",
    fileCount: 8,
    status: "enabled",
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-07-06 16:20",
    ownerName: "运行部",
    isPinned: true,
  },
  {
    id: "kb-trading-standard",
    name: "电力交易业务技术标准库",
    description: "电力交易规则、结算口径与交易执行标准",
    scope: "department",
    categoryId: "cat-run-market",
    categoryPath: ["运行专业", "交易与考核"],
    departmentId: "dept-run",
    departmentName: "运行部",
    fileCount: 128,
    status: "enabled",
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-07-06 14:30",
    ownerName: "运行部",
  },
  {
    id: "kb-public-regulation",
    name: "规章制度汇编库",
    description: "全厂共享的安全生产、运行管理与制度文件",
    scope: "public",
    categoryId: "cat-safety",
    categoryPath: ["公共制度"],
    fileCount: 18,
    status: "enabled",
    permission: {
      canView: true,
      canUpload: false,
      canManage: false,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-04 09:20",
    ownerName: "知识库管理员",
  },
  {
    id: "kb-equipment-standard",
    name: "设备技术标准库",
    description: "主设备技术规范、检修标准与试验报告",
    scope: "department",
    categoryId: "cat-tech",
    categoryPath: ["设备技术"],
    departmentId: "dept-tech",
    departmentName: "技术部",
    fileCount: 67,
    status: "enabled",
    permission: {
      canView: false,
      canUpload: false,
      canManage: false,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-03 10:10",
    ownerName: "技术部",
  },
  {
    id: "kb-dispatch-rule",
    name: "调度运行规程库",
    description: "电网调度规程、并网协议与运行协调规则",
    scope: "department",
    categoryId: "cat-dispatch",
    categoryPath: ["调度协同"],
    departmentId: "dept-dispatch",
    departmentName: "调度部",
    fileCount: 54,
    status: "enabled",
    permission: {
      canView: false,
      canUpload: false,
      canManage: false,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-02 11:30",
    ownerName: "调度部",
  },
  {
    id: "kb-history-rules",
    name: "历史规程归档库",
    description: "保留已停用的历史规程资料，仅管理端可见",
    scope: "department",
    categoryId: "cat-run-rules",
    categoryPath: ["运行专业", "规程制度"],
    departmentId: "dept-run",
    departmentName: "运行部",
    fileCount: 9,
    status: "disabled",
    permission: {
      canView: true,
      canUpload: false,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-06-12 08:30",
    ownerName: "运行部",
  },
];

export const KNOWLEDGE_FILES: KnowledgeFile[] = [
  {
    id: "file-grid-guide",
    name: "并网发电厂运行规程汇编.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["并网", "运行规程"],
    version: "v4",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 09:15",
    createdAt: "2026-07-03 09:15",
    size: "2.45MB",
    summary: "汇编并网运行日常监视、异常处置和调度联系要求。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
    versions: [
      {
        id: "file-grid-guide-v4",
        version: "v4",
        name: "2026 修订版",
        description: "当前版，参与默认 AI 问答召回",
        uploadedAt: "2026-07-07 09:15",
        uploaderName: "张工",
        isCurrent: true,
      },
      {
        id: "file-grid-guide-v3",
        version: "v3",
        name: "2025 年版",
        description: "历史版本，只读预览和下载",
        uploadedAt: "2025-12-18 09:30",
        uploaderName: "王工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-ticket",
    name: "220kV 主变停复役典型操作票.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["操作票", "主变"],
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-07-05 11:30",
    createdAt: "2026-06-25 11:30",
    size: "756KB",
    summary: "沉淀主变停复役操作节点、复核项与风险提示。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
  {
    id: "file-grid-parse-failed",
    name: "并网异常处置复盘扫描件.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["复盘", "扫描件"],
    version: "v1",
    isCurrentVersion: true,
    status: "parseFailed",
    parseStatus: "failed",
    parseError: "扫描件文字层缺失，OCR 识别失败",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 08:40",
    createdAt: "2026-07-07 08:40",
    size: "6.8MB",
    summary: "复盘一次并网异常处置过程，等待重新解析。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-dispatch-contact",
    name: "调度联系与许可操作规范.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["调度", "许可"],
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-07-04 15:22",
    createdAt: "2026-06-18 09:00",
    size: "1.08MB",
    summary: "规范调度联系用语、许可操作流程与记录要求。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-blackstart",
    name: "黑启动与孤网运行应急预案.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["应急", "黑启动"],
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-07-03 10:40",
    createdAt: "2026-05-12 11:00",
    size: "3.2MB",
    summary: "覆盖孤网场景下机组启动顺序、负荷恢复与通讯保障。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-grid-freq-control",
    name: "一次调频与频率异常处置卡.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["调频", "异常处置"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-07-02 08:18",
    createdAt: "2026-07-01 16:40",
    size: "512KB",
    summary: "一次调频异常判断条件与现场处置步骤。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-voltage",
    name: "电压控制与无功调整作业指导书.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["电压", "无功"],
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2026-06-30 14:05",
    createdAt: "2026-06-10 09:20",
    size: "1.76MB",
    summary: "母线电压越限时的无功设备投退与协调原则。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-grid-line-outage",
    name: "线路停复役操作安全交底.pptx",
    type: "pptx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["停复役", "交底"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-06-28 11:36",
    createdAt: "2026-06-28 11:36",
    size: "4.1MB",
    summary: "线路停复役前安全交底要点与风险辨识清单。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-relay-check",
    name: "并网保护定值核对表.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["保护", "定值"],
    version: "v4",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-06-26 09:12",
    createdAt: "2026-04-02 10:00",
    size: "890KB",
    summary: "并网侧保护定值核对项与修订记录模板。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-tie-line",
    name: "联络线潮流监视与越限处理.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["联络线", "潮流"],
    version: "v2",
    isCurrentVersion: true,
    status: "pendingApproval",
    parseStatus: "waiting",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 17:20",
    createdAt: "2026-07-07 17:20",
    size: "1.35MB",
    summary: "联络线潮流监视阈值与越限处置步骤，等待审批。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-unit-start",
    name: "机组并网启动操作票汇编.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["操作票", "启动"],
    version: "v5",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-06-22 16:48",
    createdAt: "2026-03-11 08:30",
    size: "2.1MB",
    summary: "冷热态启动并网典型票与关键检查点。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    versions: [
      {
        id: "file-grid-unit-start-v5",
        version: "v5",
        name: "2026 增补版",
        uploadedAt: "2026-06-22 16:48",
        uploaderName: "运行部",
        isCurrent: true,
      },
      {
        id: "file-grid-unit-start-v4",
        version: "v4",
        name: "2025 常规版",
        uploadedAt: "2025-09-08 10:00",
        uploaderName: "李工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-comm-loss",
    name: "调度通讯中断应急处置卡.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["通讯", "应急"],
    version: "v1",
    isCurrentVersion: true,
    status: "parsing",
    parseStatus: "parsing",
    uploaderName: "张工",
    updatedAt: "2026-07-07 18:05",
    createdAt: "2026-07-07 18:05",
    size: "640KB",
    summary: "主备通道路径切换与现场临时处置流程，解析中。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-weather",
    name: "恶劣天气并网运行注意事项.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["天气", "预防"],
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-06-19 13:27",
    createdAt: "2026-05-01 09:10",
    size: "2.88MB",
    summary: "雷雨大风、浓雾等天气下的巡视与限出力建议。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-grid-shift-handover",
    name: "运行交接班记录模板.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["交接班", "记录"],
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-06-15 07:50",
    createdAt: "2026-06-01 08:00",
    size: "328KB",
    summary: "标准化交接班字段与异常遗留项跟踪。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-island",
    name: "孤岛检测与解列复并试验方案.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["孤岛", "试验"],
    version: "v1",
    isCurrentVersion: true,
    status: "rejected",
    parseStatus: "waiting",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-06 11:02",
    createdAt: "2026-07-06 09:40",
    size: "960KB",
    summary: "试验方案审批驳回，需补齐安全措施与边界条件。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-rule",
    name: "AGC 考核管理办法.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["AGC", "考核"],
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-07-06 16:20",
    createdAt: "2026-06-20 08:40",
    size: "980KB",
    summary: "定义 AGC 考核指标、月度统计口径和责任分解方式。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-agc-report",
    name: "2026 年 6 月 AGC 指标统计.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["月报", "指标"],
    version: "v1",
    isCurrentVersion: true,
    status: "parsing",
    parseStatus: "parsing",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 10:12",
    createdAt: "2026-07-07 10:12",
    size: "1.1MB",
    summary: "统计 6 月 AGC 指标表现，正在解析。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-monthly-may",
    name: "2026 年 5 月 AGC 指标统计.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["月报", "指标"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-08 10:00",
    createdAt: "2026-06-08 10:00",
    size: "1.05MB",
    summary: "5 月 AGC 考核指标汇总与偏差分析。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-kpi-manual",
    name: "AGC 指标口径与算法说明.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["口径", "算法"],
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-06-25 15:40",
    createdAt: "2026-05-20 09:00",
    size: "1.4MB",
    summary: "明确可用率、调节速率、调节精度等指标计算规则。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-agc-template",
    name: "AGC 月报填报模板.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["模板", "填报"],
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2026-06-12 09:22",
    createdAt: "2026-04-18 11:10",
    size: "456KB",
    summary: "机组侧月报字段定义与报送时间要求。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-case",
    name: "AGC 不合格案例复盘.pptx",
    type: "pptx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["复盘", "案例"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-07-01 14:15",
    createdAt: "2026-07-01 14:15",
    size: "5.6MB",
    summary: "典型不合格时段归因与整改建议。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-test",
    name: "AGC 性能试验导则.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["试验", "性能"],
    version: "v4",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "运行部",
    updatedAt: "2026-05-30 16:00",
    createdAt: "2026-02-14 10:30",
    size: "2.2MB",
    summary: "升负荷/降负荷试验步骤、采样与判据。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
    versions: [
      {
        id: "file-agc-test-v4",
        version: "v4",
        name: "2026 更新版",
        uploadedAt: "2026-05-30 16:00",
        uploaderName: "运行部",
        isCurrent: true,
      },
      {
        id: "file-agc-test-v3",
        version: "v3",
        name: "2024 版",
        uploadedAt: "2024-11-02 09:20",
        uploaderName: "李工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-agc-alert",
    name: "AGC 实时告警处置手册.docx",
    type: "docx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["告警", "处置"],
    version: "v1",
    isCurrentVersion: true,
    status: "parseFailed",
    parseStatus: "failed",
    parseError: "嵌入对象损坏，文本抽取失败",
    uploaderName: "张工",
    updatedAt: "2026-07-07 12:33",
    createdAt: "2026-07-07 12:33",
    size: "1.9MB",
    summary: "告警分级与值班处置动作，解析失败待重试。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-spot-rule",
    name: "电力现货市场基本规则.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-trading-standard",
    knowledgeBaseName: "电力交易业务技术标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "电力交易",
    tags: ["现货", "交易规则"],
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-07-06 14:30",
    createdAt: "2026-07-06 14:30",
    size: "1.28MB",
    summary: "规定现货市场参与主体、交易品种、出清流程与结算边界。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
    versions: [
      {
        id: "file-spot-rule-v3",
        version: "v3",
        name: "2026 修订版",
        uploadedAt: "2026-07-06 14:30",
        uploaderName: "张工",
        isCurrent: true,
      },
      {
        id: "file-spot-rule-v2",
        version: "v2",
        name: "2025 试行版",
        description: "历史版本，不参与默认 AI 召回",
        uploadedAt: "2025-10-18 09:20",
        uploaderName: "李工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-contract",
    name: "中长期合同签订规程.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-trading-standard",
    knowledgeBaseName: "电力交易业务技术标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "电力交易",
    tags: ["中长期", "合同"],
    version: "v1",
    isCurrentVersion: true,
    status: "pendingApproval",
    parseStatus: "waiting",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 13:08",
    createdAt: "2026-07-07 13:08",
    size: "864KB",
    summary: "面向合同签订、履约调整和交易执行的操作说明，等待审批。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-public-safety",
    name: "安全生产管理规定.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-public-regulation",
    knowledgeBaseName: "规章制度汇编库",
    categoryPath: ["公共制度"],
    professionalType: "安全管理",
    tags: ["安全", "制度"],
    version: "v5",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "知识库管理员",
    updatedAt: "2026-07-04 09:20",
    createdAt: "2026-07-04 09:20",
    size: "1.62MB",
    summary: "全厂安全生产责任、制度执行、隐患闭环和检查机制。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
    favorite: false,
  },
  {
    id: "file-personal-note",
    name: "个人学习笔记汇总.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间"],
    professionalType: "个人资料",
    tags: ["个人", "学习摘录"],
    version: "v1",
    isCurrentVersion: true,
    status: "parsing",
    parseStatus: "parsing",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 19:10",
    createdAt: "2026-07-07 19:10",
    size: "856KB",
    summary: "个人学习笔记、规程摘录与待整理问题清单。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
  {
    id: "file-personal-draft",
    name: "AGC 指标复盘草稿.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间"],
    professionalType: "个人资料",
    tags: ["草稿", "AGC"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-05 20:16",
    createdAt: "2026-07-05 20:16",
    size: "420KB",
    summary: "个人整理的 AGC 指标复盘草稿，可移动到公共或专业知识库。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-personal-shift-log",
    name: "7月早班交接记录.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间", "工作笔记"],
    professionalType: "运行值班",
    tags: ["交接班", "早班"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-06 14:22",
    createdAt: "2026-07-06 08:05",
    size: "312KB",
    summary: "早班设备状态、遗留事项与当班重点关注点。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
  {
    id: "file-personal-trip-review",
    name: "主变跳闸复盘纪要.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间", "工作笔记"],
    professionalType: "异常处置",
    tags: ["跳闸", "复盘"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-04 16:48",
    createdAt: "2026-07-04 16:48",
    size: "528KB",
    summary: "主变跳闸经过、保护动作分析与后续整改跟踪。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-personal-market-note",
    name: "现货报价策略备忘.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间", "工作笔记"],
    professionalType: "电力交易",
    tags: ["现货", "报价"],
    version: "v1",
    isCurrentVersion: true,
    status: "parsing",
    parseStatus: "parsing",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 10:15",
    createdAt: "2026-07-07 10:15",
    size: "186KB",
    summary: "近期现货报价策略调整与机组出力约束备忘。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
  {
    id: "file-personal-grid-excerpt",
    name: "并网管理规程重点摘录.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-personal-study",
    knowledgeBaseName: "规程学习摘录库",
    categoryPath: ["我的空间", "学习摘录"],
    professionalType: "并网管理",
    tags: ["规程", "摘录"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-05 11:40",
    createdAt: "2026-07-03 20:30",
    size: "1.12MB",
    summary: "并网管理规程中与运行值班相关的重点条款摘录。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-personal-agc-quiz",
    name: "AGC 考核题库整理.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-personal-study",
    knowledgeBaseName: "规程学习摘录库",
    categoryPath: ["我的空间", "学习摘录"],
    professionalType: "AGC 考核",
    tags: ["题库", "自测"],
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-02 19:05",
    createdAt: "2026-07-02 19:05",
    size: "244KB",
    summary: "AGC 考核常见题型与易错点整理，用于班组自测复习。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
];

export const PERSONAL_DIRECTORIES: PersonalDirectory[] = [
  { id: "personal-root", name: "个人目录" },
  { id: "personal-work", parentId: "personal-root", name: "工作笔记" },
  { id: "personal-study", parentId: "personal-root", name: "学习摘录" },
];

export const RECENT_FILE_IDS = [
  "file-grid-guide",
  "file-agc-rule",
  "file-personal-shift-log",
  "file-personal-trip-review",
  "file-personal-grid-excerpt",
];

export const FAVORITE_FILE_IDS = [
  "file-grid-guide",
  "file-personal-trip-review",
  "file-personal-grid-excerpt",
  "file-personal-draft",
];

export const UPLOAD_RECORDS: UploadRecord[] = [
  {
    id: "upload-contract",
    fileId: "file-contract",
    fileName: "中长期合同签订规程.pdf",
    targetKnowledgeBaseName: "电力交易业务技术标准库",
    submittedAt: "2026-07-07 13:08",
    status: "pendingApproval",
  },
  {
    id: "upload-personal-note",
    fileId: "file-personal-note",
    fileName: "个人学习笔记汇总.docx",
    targetKnowledgeBaseName: "运行值班笔记库",
    submittedAt: "2026-07-07 19:10",
    status: "parsing",
  },
  {
    id: "upload-agc-report",
    fileId: "file-agc-rule",
    fileName: "AGC 考核标准细则.pdf",
    targetKnowledgeBaseName: "AGC 考核标准库",
    submittedAt: "2026-07-06 09:42",
    status: "published",
  },
  {
    id: "upload-market-note",
    fileId: "file-personal-market-note",
    fileName: "现货报价策略备忘.xlsx",
    targetKnowledgeBaseName: "运行值班笔记库",
    submittedAt: "2026-07-07 10:15",
    status: "parsing",
  },
  {
    id: "upload-rejected",
    fileId: "file-public-safety",
    fileName: "典型经验汇编.pdf",
    targetKnowledgeBaseName: "规章制度汇编库",
    submittedAt: "2026-07-02 08:10",
    status: "rejected",
    rejectReason: "资料来源和审批依据不完整，请补充后重新提交。",
  },
];

export const UPLOAD_APPROVALS: UploadApproval[] = [
  {
    id: "approval-contract",
    fileName: "中长期合同签订规程.pdf",
    knowledgeBaseName: "电力交易业务技术标准库",
    departmentName: "运行部",
    submitterName: "张工",
    submittedAt: "2026-07-07 13:08",
    fileSize: "2.4 MB",
    uploadNote: "补充交易执行口径说明",
    riskHint: "同名文件，建议作为新版本上传",
  },
  {
    id: "approval-agc-report",
    fileName: "AGC 指标月报补充说明.docx",
    knowledgeBaseName: "AGC 考核标准库",
    departmentName: "运行部",
    submitterName: "李工",
    submittedAt: "2026-07-07 09:28",
    fileSize: "856 KB",
    uploadNote: "月度统计方法更新",
  },
];

export const PERMISSION_REQUESTS: PermissionRequest[] = [
  {
    id: "perm-equipment",
    applicantName: "张工",
    knowledgeBaseId: "kb-equipment-standard",
    knowledgeBaseName: "设备技术标准库",
    group: "view",
    reason: "需要查阅主设备试验标准，用于并网异常复盘。",
    submittedAt: "2026-07-07 11:30",
    notifyStatus: "waiting",
  },
  {
    id: "perm-dispatch",
    applicantName: "陈工",
    knowledgeBaseId: "kb-dispatch-rule",
    knowledgeBaseName: "调度运行规程库",
    group: "upload",
    reason: "补充联络线协调记录模板。",
    submittedAt: "2026-07-06 16:40",
    notifyStatus: "sent",
  },
];

export const PERMISSION_MEMBERS: Record<string, PermissionMember[]> = {
  "kb-grid-operation": [
    { id: "u-run-admin", name: "张工", group: "manage" },
    { id: "u-li", name: "李工", group: "upload" },
  ],
  "kb-agc": [
    { id: "u-run-admin", name: "张工", group: "manage" },
    { id: "u-chen", name: "陈工", group: "view" },
  ],
};

export const PARSE_EXCEPTIONS: ParseException[] = [
  {
    id: "parse-grid-scan",
    fileId: "file-grid-parse-failed",
    fileName: "并网异常处置复盘扫描件.pdf",
    knowledgeBaseName: "并网运行管理库",
    uploadedAt: "2026-07-07 08:40",
    reason: "扫描件文字层缺失，OCR 识别失败",
    failureType: "ocr",
    fileSize: "4.2 MB",
    version: "v1",
  },
  {
    id: "parse-agc-upload",
    fileId: "file-agc-report",
    fileName: "AGC 指标统计附件.xlsx",
    knowledgeBaseName: "AGC 考核标准库",
    uploadedAt: "2026-07-07 10:12",
    reason: "工作表合并单元格过多，解析任务超时",
    failureType: "timeout",
    fileSize: "1.1 MB",
    version: "v2",
  },
];
