import type {
  FileMoveApproval,
  KnowledgeBase,
  KnowledgeCategory,
  KnowledgeFile,
  KnowledgeUser,
  ParseException,
  PermissionMember,
  PermissionRequest,
  PersonalDirectory,
  UploadApproval,
  UploadRecord,
} from "./types";

export const CURRENT_KNOWLEDGE_USER: KnowledgeUser = {
  id: "u-run-admin",
  name: "张工",
  role: "knowledgeAdmin",
};

export const KNOWLEDGE_CATEGORIES: KnowledgeCategory[] = [
  { id: "cat-run", name: "运行专业" },
  { id: "cat-run-rules", parentId: "cat-run", name: "规程制度" },
  { id: "cat-run-market", parentId: "cat-run", name: "交易与考核" },
  { id: "cat-dispatch", name: "调度协同" },
  { id: "cat-tech", name: "设备技术" },
  { id: "cat-safety", name: "公共制度规程" },
];

export const KNOWLEDGE_BASES: KnowledgeBase[] = [
  {
    id: "kb-personal-work",
    name: "运行值班笔记库",
    description: "值班记录、异常处置复盘与班组交接要点",
    scope: "personal",
    personalDirectoryId: "personal-work",
    fileCount: 5,
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-07 19:10",
    ownerName: "张工",
    isPinned: true,
    metadataFields: [
      {
        id: "noteType",
        label: "笔记类型",
        type: "select",
        options: ["值班记录", "异常复盘", "交接班", "备忘", "草稿"],
      },
      {
        id: "shift",
        label: "班次",
        type: "select",
        options: ["早班", "中班", "夜班", "不涉及"],
      },
      {
        id: "topic",
        label: "主题",
        type: "select",
        options: ["运行监视", "异常处置", "AGC", "电力交易", "设备故障"],
      },
    ],
  },
  {
    id: "kb-personal-study",
    name: "规程学习摘录库",
    description: "并网规程摘录、考核要点与培训复习材料",
    scope: "personal",
    personalDirectoryId: "personal-study",
    fileCount: 2,
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-05 11:40",
    ownerName: "张工",
    metadataFields: [
      {
        id: "source",
        label: "来源",
        type: "select",
        options: ["规程摘录", "培训材料", "题库整理", "外部资料"],
      },
      {
        id: "subject",
        label: "学习主题",
        type: "select",
        options: ["并网管理", "AGC 考核", "电力交易", "安全规程", "设备技术"],
      },
      {
        id: "progress",
        label: "学习进度",
        type: "select",
        options: ["未开始", "学习中", "已掌握", "待复习"],
      },
    ],
  },
  {
    id: "kb-grid-operation",
    name: "并网运行管理库",
    description: "并网运行规程、典型操作票与异常处置经验资料",
    scope: "professional",
    categoryId: "cat-run-rules",
    categoryPath: ["运行专业", "规程制度"],
    fileCount: 22,
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-07-07 09:15",
    ownerName: "张工",
    isPinned: true,
    metadataFields: [
      {
        id: "docType",
        label: "文档类型",
        type: "select",
        options: ["运行规程", "操作票", "作业指导书", "应急预案", "复盘记录", "记录模板", "核对表"],
      },
      {
        id: "segment",
        label: "业务环节",
        type: "select",
        options: ["启停操作", "调度联系", "异常处置", "继电保护", "电压频率", "交接班", "试验"],
      },
      {
        id: "voltage",
        label: "电压等级",
        type: "select",
        options: ["500kV", "220kV", "全厂", "不涉及"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
  {
    id: "kb-agc",
    name: "AGC 考核标准库",
    description: "AGC 考核指标、实施细则与月度统计方法",
    scope: "professional",
    categoryId: "cat-run-market",
    categoryPath: ["运行专业", "交易与考核"],
    fileCount: 10,
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-07-06 16:20",
    ownerName: "张工",
    isPinned: true,
    metadataFields: [
      {
        id: "docType",
        label: "文档类型",
        type: "select",
        options: ["规程制度", "统计报表", "填报模板", "案例复盘", "技术说明", "操作手册"],
      },
      {
        id: "period",
        label: "适用周期",
        type: "select",
        options: ["月度", "季度", "年度", "通用"],
      },
      {
        id: "topic",
        label: "业务主题",
        type: "select",
        options: ["考核指标", "算法口径", "告警处置", "性能试验", "数据填报"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
  {
    id: "kb-trading-standard",
    name: "电力交易业务技术标准库",
    description: "电力交易规则、结算口径与交易执行标准",
    scope: "professional",
    categoryId: "cat-run-market",
    categoryPath: ["运行专业", "交易与考核"],
    fileCount: 128,
    permission: {
      canView: true,
      canUpload: true,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-07-06 14:30",
    ownerName: "张工",
    metadataFields: [
      {
        id: "docType",
        label: "文档类型",
        type: "select",
        options: ["交易规则", "结算规则", "合同范本", "技术标准", "操作说明"],
      },
      {
        id: "tradeType",
        label: "交易类型",
        type: "select",
        options: ["现货市场", "中长期", "辅助服务", "绿电交易"],
      },
      {
        id: "effectiveYear",
        label: "适用年度",
        type: "select",
        options: ["2024", "2025", "2026", "长期有效"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
  {
    id: "kb-trading-review",
    name: "电力交易内部评审库",
    description: "交易方案内部评审材料，仅授权岗位可浏览",
    scope: "professional",
    categoryId: "cat-run-market",
    categoryPath: ["运行专业", "交易与考核"],
    fileCount: 6,
    permission: {
      canView: false,
      canUpload: false,
      canManage: false,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-05 09:40",
    ownerName: "张工",
    metadataFields: [
      {
        id: "docType",
        label: "文档类型",
        type: "select",
        options: ["评审意见", "方案材料", "会议纪要", "批复文件"],
      },
      {
        id: "tradeType",
        label: "交易类型",
        type: "select",
        options: ["现货市场", "中长期", "辅助服务"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
  {
    id: "kb-public-regulation",
    name: "规章制度汇编库",
    description: "全厂共享的安全生产、运行管理与制度文件",
    scope: "public",
    categoryId: "cat-safety",
    categoryPath: ["公共制度规程"],
    fileCount: 18,
    permission: {
      canView: true,
      canUpload: false,
      canManage: false,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-04 09:20",
    ownerName: "知识库管理员",
    metadataFields: [
      {
        id: "category",
        label: "制度类别",
        type: "select",
        options: ["安全生产", "运行管理", "综合行政", "应急管理", "环保节能"],
      },
      {
        id: "department",
        label: "归口部门",
        type: "select",
        options: ["安全监察部", "生产技术部", "综合管理部", "应急指挥中心"],
      },
      {
        id: "secrecy",
        label: "密级",
        type: "select",
        options: ["公开", "内部公开"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
  {
    id: "kb-equipment-standard",
    name: "设备技术标准库",
    description: "主设备技术规范、检修标准与试验报告",
    scope: "professional",
    categoryId: "cat-tech",
    categoryPath: ["设备技术"],
    fileCount: 0,
    permission: {
      canView: true,
      canUpload: true,
      canManage: false,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-03 10:10",
    ownerName: "王工",
    metadataFields: [
      {
        id: "equipmentType",
        label: "设备类型",
        type: "select",
        options: ["主变压器", "汽轮机", "发电机", "锅炉", "开关设备", "辅机系统"],
      },
      {
        id: "docType",
        label: "文档类型",
        type: "select",
        options: ["技术规范", "检修标准", "试验报告", "设备说明书", "反措要求"],
      },
      {
        id: "voltage",
        label: "电压等级/规格",
        type: "select",
        options: ["500kV", "220kV", "其他"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
  {
    id: "kb-dispatch-rule",
    name: "调度运行规程库",
    description: "电网调度规程、并网协议与运行协调规则",
    scope: "professional",
    categoryId: "cat-dispatch",
    categoryPath: ["调度协同"],
    fileCount: 54,
    restricted: true,
    permission: {
      canView: false,
      canUpload: false,
      canManage: false,
      canConfigurePermission: false,
    },
    updatedAt: "2026-07-02 11:30",
    ownerName: "李工",
    metadataFields: [
      {
        id: "docType",
        label: "文档类型",
        type: "select",
        options: ["调度规程", "并网协议", "协调规则", "调度预案", "通知通告"],
      },
      {
        id: "scope",
        label: "适用范围",
        type: "select",
        options: ["省调", "地调", "厂内"],
      },
      {
        id: "validity",
        label: "时效",
        type: "select",
        options: ["长期有效", "年度", "临时"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
  {
    id: "kb-history-rules",
    name: "历史规程归档库",
    description: "历史规程归档资料，便于查阅过往版本",
    scope: "professional",
    categoryId: "cat-run-rules",
    categoryPath: ["运行专业", "规程制度"],
    fileCount: 9,
    permission: {
      canView: true,
      canUpload: false,
      canManage: true,
      canConfigurePermission: true,
    },
    updatedAt: "2026-06-12 08:30",
    ownerName: "张工",
    metadataFields: [
      {
        id: "category",
        label: "归档类别",
        type: "select",
        options: ["运行规程", "操作规程", "管理制度", "技术标准"],
      },
      {
        id: "originalYear",
        label: "原生效年度",
        type: "select",
        options: ["2020", "2021", "2022", "2023"],
      },
      {
        id: "archiveStatus",
        label: "归档状态",
        type: "select",
        options: ["已废止", "被替代", "仅归档"],
      },
      {
        id: "docNo",
        label: "文号/编号",
        type: "text",
      },
    ],
  },
];

export const KNOWLEDGE_FILES: KnowledgeFile[] = [
  {
    id: "file-grid-guide",
    name: "并网发电厂运行规程汇编.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["并网", "运行规程"],
    metadata: { docType: "运行规程", segment: "启停操作", voltage: "全厂", docNo: "GRID-2026-001" },
    version: "v4",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 09:15",
    createdAt: "2026-07-03 09:15",
    size: "2.45MB",
    summary:
      "汇编并网发电厂总则、日常监视、调度联系、异常事故处置、调频调压、检修与二次管理、启停倒闸及交接班要求，依据《电力并网运行管理规定》整理供值班查阅。",
    fullTextContent:
      "并网发电厂运行规程 总则 适用范围 统一调度 日常监视 发电机 主变 升压站 调度指令 复诵回令 AGC 一次调频 AVC 异常汇报 事故处置 不得擅自并网 检修计划 保护定值 两票三制 交接班 反事故措施 黑启动",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
    versions: [
      {
        id: "file-grid-guide-v4",
        version: "v4",
        name: "2026 修订版",
        description: "当前版，参与默认 AI 问答召回",
        uploadedAt: "2026-07-07 09:15",
        uploaderName: "张工",
        isCurrent: true,
      },
      {
        id: "file-grid-guide-v3",
        version: "v3",
        name: "2025 年版",
        description: "历史版本，只读预览和下载",
        uploadedAt: "2025-12-18 09:30",
        uploaderName: "王工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-ticket",
    name: "220kV 主变停复役典型操作票.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["操作票", "主变"],
    metadata: { docType: "操作票", segment: "启停操作", voltage: "220kV", docNo: "OP-220-015" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-07-05 11:30",
    createdAt: "2026-06-25 11:30",
    size: "756KB",
    summary: "沉淀主变停复役操作节点、复核项与风险提示。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
    versions: [
      {
        id: "file-grid-ticket-v2",
        version: "v2",
        name: "2026 修订版",
        uploadedAt: "2026-07-05 11:30",
        uploaderName: "张工",
        isCurrent: true,
      },
      {
        id: "file-grid-ticket-v1",
        version: "v1",
        name: "初版",
        uploadedAt: "2026-06-25 11:30",
        uploaderName: "张工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-parse-failed",
    name: "并网异常处置复盘扫描件.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["复盘", "扫描件"],
    metadata: { docType: "复盘记录", segment: "异常处置", voltage: "全厂" },
    version: "v1",
    isCurrentVersion: true,
    status: "parseFailed",
    parseStatus: "failed",
    parseError: "扫描件文字层缺失，OCR 识别失败",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 08:40",
    createdAt: "2026-07-07 08:40",
    size: "6.8MB",
    summary: "复盘一次并网异常处置过程，等待重新解析。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-dispatch-contact",
    name: "调度联系与许可操作规范.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["调度", "许可"],
    metadata: { docType: "运行规程", segment: "调度联系", voltage: "全厂", docNo: "DISP-2026-003" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-07-04 15:22",
    createdAt: "2026-06-18 09:00",
    size: "1.08MB",
    summary: "规范调度联系用语、许可操作流程与记录要求。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-blackstart",
    name: "黑启动与孤网运行应急预案.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["应急", "黑启动"],
    metadata: { docType: "应急预案", segment: "异常处置", voltage: "全厂", docNo: "EMG-2026-001" },
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-07-03 10:40",
    createdAt: "2026-05-12 11:00",
    size: "3.2MB",
    summary: "覆盖孤网场景下机组启动顺序、负荷恢复与通讯保障。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-grid-freq-control",
    name: "一次调频与频率异常处置卡.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["调频", "异常处置"],
    metadata: { docType: "作业指导书", segment: "电压频率", voltage: "全厂" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-07-02 08:18",
    createdAt: "2026-07-01 16:40",
    size: "512KB",
    summary: "一次调频异常判断条件与现场处置步骤。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-voltage",
    name: "电压控制与无功调整作业指导书.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["电压", "无功"],
    metadata: { docType: "作业指导书", segment: "电压频率", voltage: "500kV" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2026-06-30 14:05",
    createdAt: "2026-06-10 09:20",
    size: "1.76MB",
    summary: "母线电压越限时的无功设备投退与协调原则。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-grid-line-outage",
    name: "线路停复役操作安全交底.pptx",
    type: "pptx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["停复役", "交底"],
    metadata: { docType: "操作票", segment: "启停操作", voltage: "220kV" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-28 11:36",
    createdAt: "2026-06-28 11:36",
    size: "4.1MB",
    summary: "线路停复役前安全交底要点与风险辨识清单。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-relay-check",
    name: "并网保护定值核对表.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["保护", "定值"],
    metadata: { docType: "核对表", segment: "继电保护", voltage: "500kV", docNo: "RELAY-2026-008" },
    version: "v4",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-06-26 09:12",
    createdAt: "2026-04-02 10:00",
    size: "890KB",
    summary: "并网侧保护定值核对项与修订记录模板。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-tie-line",
    name: "联络线潮流监视与越限处理.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["联络线", "潮流"],
    metadata: { docType: "运行规程", segment: "异常处置", voltage: "500kV" },
    version: "v2",
    isCurrentVersion: true,
    status: "pendingApproval",
    parseStatus: "waiting",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 17:20",
    createdAt: "2026-07-07 17:20",
    size: "1.35MB",
    summary: "联络线潮流监视阈值与越限处置步骤，等待审批。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-unit-start",
    name: "机组并网启动操作票汇编.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["操作票", "启动"],
    metadata: { docType: "操作票", segment: "启停操作", voltage: "全厂", docNo: "OP-START-2026" },
    version: "v5",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-22 16:48",
    createdAt: "2026-03-11 08:30",
    size: "2.1MB",
    summary: "冷热态启动并网典型票与关键检查点。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    versions: [
      {
        id: "file-grid-unit-start-v5",
        version: "v5",
        name: "2026 增补版",
        uploadedAt: "2026-06-22 16:48",
        uploaderName: "张工",
        isCurrent: true,
      },
      {
        id: "file-grid-unit-start-v4",
        version: "v4",
        name: "2025 常规版",
        uploadedAt: "2025-09-08 10:00",
        uploaderName: "李工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-comm-loss",
    name: "调度通讯中断应急处置卡.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["通讯", "应急"],
    metadata: { docType: "应急预案", segment: "调度联系", voltage: "全厂" },
    version: "v1",
    isCurrentVersion: true,
    status: "parsing",
    parseStatus: "parsing",
    uploaderName: "张工",
    updatedAt: "2026-07-07 18:05",
    createdAt: "2026-07-07 18:05",
    size: "640KB",
    summary: "主备通道路径切换与现场临时处置流程，解析中。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-weather",
    name: "恶劣天气并网运行注意事项.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["天气", "预防"],
    metadata: { docType: "运行规程", segment: "异常处置", voltage: "全厂" },
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-06-19 13:27",
    createdAt: "2026-05-01 09:10",
    size: "2.88MB",
    summary: "雷雨大风、浓雾等天气下的巡视与限出力建议。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-grid-shift-handover",
    name: "运行交接班记录模板.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["交接班", "记录"],
    metadata: { docType: "记录模板", segment: "交接班", voltage: "不涉及" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-15 07:50",
    createdAt: "2026-06-01 08:00",
    size: "328KB",
    summary: "标准化交接班字段与异常遗留项跟踪。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-island",
    name: "孤岛检测与解列复并试验方案.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["孤岛", "试验"],
    metadata: { docType: "复盘记录", segment: "试验", voltage: "全厂" },
    version: "v1",
    isCurrentVersion: true,
    status: "rejected",
    parseStatus: "waiting",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-06 11:02",
    createdAt: "2026-07-06 09:40",
    size: "960KB",
    summary: "试验方案审批驳回，需补齐安全措施与边界条件。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-avs-curve",
    name: "自动电压控制AVC曲线整定与监视要点.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["AVC", "电压"],
    metadata: { docType: "作业指导书", segment: "电压频率", voltage: "500kV" },
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2026-07-01 13:20",
    createdAt: "2026-05-08 09:10",
    size: "1.42MB",
    summary: "AVC 曲线整定边界、监视指标与异常退运条件。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    versions: [
      {
        id: "file-grid-avs-curve-v3",
        version: "v3",
        name: "2026 修订版",
        uploadedAt: "2026-07-01 13:20",
        uploaderName: "李工",
        isCurrent: true,
      },
      {
        id: "file-grid-avs-curve-v2",
        version: "v2",
        name: "2025 年版",
        uploadedAt: "2025-11-02 10:00",
        uploaderName: "王工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-fault-recorder",
    name: "故障录波调阅与事故简报编制规范.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["录波", "事故简报"],
    metadata: { docType: "运行规程", segment: "异常处置", voltage: "全厂" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-29 09:45",
    createdAt: "2026-04-16 14:20",
    size: "1.18MB",
    summary: "规定录波调阅时限、简报字段与报送路径。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-load-shedding",
    name: "低频低压减载装置投退与定值核对表.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["减载", "定值"],
    metadata: { docType: "核对表", segment: "继电保护", voltage: "220kV" },
    version: "v4",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-06-27 16:10",
    createdAt: "2026-03-20 11:00",
    size: "640KB",
    summary: "减载轮次、动作定值与投退状态核对清单。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    versions: [
      {
        id: "file-grid-load-shedding-v4",
        version: "v4",
        name: "2026 核对版",
        uploadedAt: "2026-06-27 16:10",
        uploaderName: "王工",
        isCurrent: true,
      },
      {
        id: "file-grid-load-shedding-v3",
        version: "v3",
        name: "春季核对版",
        uploadedAt: "2026-03-20 11:00",
        uploaderName: "王工",
        isCurrent: false,
      },
      {
        id: "file-grid-load-shedding-v2",
        version: "v2",
        name: "2025 年版",
        uploadedAt: "2025-09-12 09:30",
        uploaderName: "李工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-bus-transfer",
    name: "母线倒闸操作风险辨识与控制措施清单.pptx",
    type: "pptx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["倒闸", "风险辨识"],
    metadata: { docType: "操作票", segment: "启停操作", voltage: "220kV" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-25 10:28",
    createdAt: "2026-06-25 10:28",
    size: "5.6MB",
    summary: "母线倒闸典型风险点与现场控制措施。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-reactive-device",
    name: "电容器电抗器投切与谐波监测作业卡.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["无功", "谐波"],
    metadata: { docType: "作业指导书", segment: "电压频率", voltage: "全厂" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2026-06-24 15:40",
    createdAt: "2026-05-30 08:50",
    size: "980KB",
    summary: "无功设备投切条件、谐波越限处置与记录要求。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-grid-sync-check",
    name: "同期装置检查与并网条件确认表.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["同期", "并网"],
    metadata: { docType: "核对表", segment: "启停操作", voltage: "全厂" },
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-21 11:05",
    createdAt: "2026-02-14 09:00",
    size: "420KB",
    summary: "同期电压、频率、相角检查项与并网确认签字栏。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    versions: [
      {
        id: "file-grid-sync-check-v3",
        version: "v3",
        name: "2026 增补版",
        uploadedAt: "2026-06-21 11:05",
        uploaderName: "张工",
        isCurrent: true,
      },
      {
        id: "file-grid-sync-check-v2",
        version: "v2",
        name: "2025 年版",
        uploadedAt: "2025-08-08 14:20",
        uploaderName: "王工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-grid-emergency-load",
    name: "事故拉路与紧急限电序位表及执行说明.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["限电", "事故拉路"],
    metadata: { docType: "应急预案", segment: "异常处置", voltage: "全厂", docNo: "EMG-LOAD-2026" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-06-19 17:30",
    createdAt: "2026-04-01 10:15",
    size: "1.05MB",
    summary: "紧急限电序位、执行条件与调度确认流程。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-grid-ice-cover",
    name: "覆冰舞动气象预警与线路特巡处置手册.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["覆冰", "特巡"],
    metadata: { docType: "应急预案", segment: "异常处置", voltage: "500kV" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2026-06-18 08:55",
    createdAt: "2026-06-18 08:55",
    size: "2.88MB",
    summary: "覆冰预警分级、特巡路线与临时运行方式调整建议。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-grid-protection-trip",
    name: "保护动作跳闸后现场检查与复电条件确认.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["保护", "复电"],
    metadata: { docType: "作业指导书", segment: "异常处置", voltage: "220kV" },
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-16 14:12",
    createdAt: "2026-05-05 09:40",
    size: "735KB",
    summary: "跳闸后检查项、试送条件与调度汇报要点。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-rule",
    name: "AGC 考核管理办法.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["AGC", "考核"],
    metadata: { docType: "规程制度", period: "通用", topic: "考核指标", docNo: "AGC-2026-001" },
    fullTextContent: "AGC 自动发电控制 考核管理办法 指标 月度统计 责任分解",
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-07-06 16:20",
    createdAt: "2026-06-20 08:40",
    size: "980KB",
    summary: "定义 AGC 考核指标、月度统计口径和责任分解方式。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-agc-report",
    name: "2026 年 6 月 AGC 指标统计.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["月报", "指标"],
    metadata: { docType: "统计报表", period: "月度", topic: "考核指标", docNo: "AGC-MON-202606" },
    fullTextContent: "2026年6月 AGC 指标统计 可用率 调节速率 调节精度",
    version: "v1",
    isCurrentVersion: true,
    status: "parsing",
    parseStatus: "parsing",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 10:12",
    createdAt: "2026-07-07 10:12",
    size: "1.1MB",
    summary: "统计 6 月 AGC 指标表现，正在解析。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-monthly-may",
    name: "2026 年 5 月 AGC 指标统计.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["月报", "指标"],
    metadata: { docType: "统计报表", period: "月度", topic: "考核指标", docNo: "AGC-MON-202606" },
    fullTextContent: "2026年5月 AGC 指标统计 偏差分析",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-08 10:00",
    createdAt: "2026-06-08 10:00",
    size: "1.05MB",
    summary: "5 月 AGC 考核指标汇总与偏差分析。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-kpi-manual",
    name: "AGC 指标口径与算法说明.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["口径", "算法"],
    metadata: { docType: "技术说明", period: "通用", topic: "算法口径" },
    fullTextContent: "AGC 指标口径 算法说明 可用率 调节速率 调节精度 计算规则",
    version: "v2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-06-25 15:40",
    createdAt: "2026-05-20 09:00",
    size: "1.4MB",
    summary: "明确可用率、调节速率、调节精度等指标计算规则。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-agc-template",
    name: "AGC 月报填报模板.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["模板", "填报"],
    metadata: { docType: "填报模板", period: "月度", topic: "数据填报" },
    fullTextContent: "AGC 月报填报模板 字段定义 报送时间",
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2026-06-12 09:22",
    createdAt: "2026-04-18 11:10",
    size: "456KB",
    summary: "机组侧月报字段定义与报送时间要求。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-case",
    name: "AGC 不合格案例复盘.pptx",
    type: "pptx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["复盘", "案例"],
    metadata: { docType: "案例复盘", period: "通用", topic: "考核指标" },
    fullTextContent: "AGC 不合格案例 复盘 整改建议 典型时段",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2026-07-01 14:15",
    createdAt: "2026-07-01 14:15",
    size: "5.6MB",
    summary: "典型不合格时段归因与整改建议。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-agc-test",
    name: "AGC 性能试验导则.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["试验", "性能"],
    metadata: { docType: "技术说明", period: "通用", topic: "性能试验" },
    fullTextContent: "AGC 性能试验导则 升负荷 降负荷 采样 判据",
    enabled: false,
    version: "v4",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-05-30 16:00",
    createdAt: "2026-02-14 10:30",
    size: "2.2MB",
    summary: "升负荷/降负荷试验步骤、采样与判据。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-agc-alert",
    name: "AGC 实时告警处置手册.docx",
    type: "docx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["告警", "处置"],
    metadata: { docType: "操作手册", period: "通用", topic: "告警处置" },
    fullTextContent: "AGC 实时告警 处置手册 告警分级 响应流程",
    version: "v1",
    isCurrentVersion: true,
    status: "parseFailed",
    parseStatus: "failed",
    parseError: "嵌入对象损坏，文本抽取失败",
    uploaderName: "张工",
    updatedAt: "2026-07-07 12:33",
    createdAt: "2026-07-07 12:33",
    size: "1.9MB",
    summary: "告警分级与值班处置动作，解析失败待重试。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-spot-rule",
    name: "电力现货市场基本规则.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-trading-standard",
    knowledgeBaseName: "电力交易业务技术标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "电力交易",
    tags: ["现货", "交易规则"],
    metadata: { docType: "交易规则", tradeType: "现货市场", effectiveYear: "2026", docNo: "TRD-SPOT-2026" },
    version: "v3",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2026-07-06 14:30",
    createdAt: "2026-07-06 14:30",
    size: "1.28MB",
    summary: "规定现货市场参与主体、交易品种、出清流程与结算边界。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
    versions: [
      {
        id: "file-spot-rule-v3",
        version: "v3",
        name: "2026 修订版",
        uploadedAt: "2026-07-06 14:30",
        uploaderName: "张工",
        isCurrent: true,
      },
      {
        id: "file-spot-rule-v2",
        version: "v2",
        name: "2025 试行版",
        description: "历史版本，不参与默认 AI 召回",
        uploadedAt: "2025-10-18 09:20",
        uploaderName: "李工",
        isCurrent: false,
      },
    ],
  },
  {
    id: "file-contract",
    name: "中长期合同签订规程.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-trading-standard",
    knowledgeBaseName: "电力交易业务技术标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "电力交易",
    tags: ["中长期", "合同"],
    metadata: { docType: "合同范本", tradeType: "中长期", effectiveYear: "2026" },
    version: "v1",
    isCurrentVersion: true,
    status: "pendingApproval",
    parseStatus: "success",
    docParseStatus: "success",
    aiParseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 13:08",
    createdAt: "2026-07-07 13:08",
    size: "864KB",
    summary: "面向合同签订、履约调整和交易执行的操作说明，等待审批。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-storage-cad",
    name: "主变竣工图纸包.dwg",
    type: "other",
    knowledgeBaseId: "kb-equipment-standard",
    knowledgeBaseName: "设备技术标准库",
    categoryPath: ["设备专业", "竣工资料"],
    professionalType: "设备",
    tags: ["竣工图", "仅存储"],
    metadata: { docType: "竣工图纸", format: "CAD" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    docParseStatus: "skipped",
    aiParseStatus: "skipped",
    storageOnly: true,
    uploaderName: "赵工",
    updatedAt: "2026-07-03 14:10",
    createdAt: "2026-07-03 14:10",
    size: "18.6MB",
    summary: "主变竣工图纸原始文件，不支持在线预览与智能检索。",
    canPreview: false,
    canDownload: true,
    canEdit: false,
  },
  {
    id: "file-personal-scan",
    name: "值班笔记扫描件.jpg",
    type: "other",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["个人笔记"],
    version: "v1",
    isCurrentVersion: true,
    status: "parseFailed",
    parseStatus: "failed",
    docParseStatus: "failed",
    aiParseStatus: "waiting",
    parseError: "图片分辨率过低，文档解析引擎无法提取有效文本",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-06 22:15",
    createdAt: "2026-07-06 22:15",
    size: "820KB",
    summary: "值班笔记扫描件，解析失败待重试。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-public-safety",
    name: "安全生产管理规定.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-public-regulation",
    knowledgeBaseName: "规章制度汇编库",
    categoryPath: ["公共制度规程"],
    professionalType: "安全管理",
    tags: ["安全", "制度"],
    metadata: { category: "安全生产", department: "安全监察部", secrecy: "公开", docNo: "SAFE-2026-001" },
    version: "v5",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "知识库管理员",
    updatedAt: "2026-07-04 09:20",
    createdAt: "2026-07-04 09:20",
    size: "1.62MB",
    summary: "全厂安全生产责任、制度执行、隐患闭环和检查机制。",
    canPreview: true,
    canDownload: true,
    canEdit: false,
    favorite: false,
  },
  {
    id: "file-personal-note",
    name: "个人学习笔记汇总.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间"],
    professionalType: "个人资料",
    tags: ["个人", "学习摘录"],
    metadata: { noteType: "备忘", shift: "不涉及", topic: "运行监视" },
    version: "v1",
    isCurrentVersion: true,
    status: "pendingConfirm",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 19:28",
    createdAt: "2026-07-07 19:10",
    size: "856KB",
    summary: "个人学习笔记、规程摘录与待整理问题清单。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    aiKeywords: ["学习笔记", "运行规程", "待整理"],
    favorite: false,
  },
  {
    id: "file-personal-draft",
    name: "AGC 指标复盘草稿.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间"],
    professionalType: "个人资料",
    tags: ["草稿", "AGC"],
    metadata: { noteType: "草稿", shift: "不涉及", topic: "AGC" },
    version: "v1",
    isCurrentVersion: true,
    status: "pendingConfirm",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-05 20:40",
    createdAt: "2026-07-05 20:16",
    size: "420KB",
    summary: "个人整理的 AGC 指标复盘草稿，可提交到公共知识库。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    aiKeywords: ["AGC", "指标复盘", "草稿"],
    favorite: true,
  },
  {
    id: "file-personal-shift-log",
    name: "7月早班交接记录.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间", "工作笔记"],
    professionalType: "运行值班",
    tags: ["交接班", "早班"],
    metadata: { noteType: "交接班", shift: "早班", topic: "运行监视" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-06 14:22",
    createdAt: "2026-07-06 08:05",
    size: "312KB",
    summary: "早班设备状态、遗留事项与当班重点关注点。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
  {
    id: "file-personal-trip-review",
    name: "主变跳闸复盘纪要.docx",
    type: "docx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间", "工作笔记"],
    professionalType: "异常处置",
    tags: ["跳闸", "复盘"],
    metadata: { noteType: "异常复盘", shift: "中班", topic: "设备故障" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-04 16:48",
    createdAt: "2026-07-04 16:48",
    size: "528KB",
    summary: "主变跳闸经过、保护动作分析与后续整改跟踪。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-personal-market-note",
    name: "现货报价策略备忘.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-personal-work",
    knowledgeBaseName: "运行值班笔记库",
    categoryPath: ["我的空间", "工作笔记"],
    professionalType: "电力交易",
    tags: ["现货", "报价"],
    metadata: { noteType: "备忘", shift: "不涉及", topic: "电力交易" },
    version: "v1",
    isCurrentVersion: true,
    status: "parsing",
    parseStatus: "parsing",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 10:15",
    createdAt: "2026-07-07 10:15",
    size: "186KB",
    summary: "近期现货报价策略调整与机组出力约束备忘。",
    canPreview: false,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
  {
    id: "file-personal-grid-excerpt",
    name: "并网管理规程重点摘录.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "并网运行"],
    professionalType: "并网管理",
    tags: ["规程", "摘录"],
    metadata: { source: "个人库移入", subject: "并网管理", progress: "待入库确认" },
    version: "v1",
    isCurrentVersion: true,
    status: "pendingApproval",
    parseStatus: "success",
    docParseStatus: "success",
    aiParseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-07 12:30",
    createdAt: "2026-07-03 20:30",
    size: "1.12MB",
    summary: "并网管理规程中与运行值班相关的重点条款摘录（自个人库移入后重解析）。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-personal-agc-quiz",
    name: "AGC 考核题库整理.xlsx",
    type: "xlsx",
    knowledgeBaseId: "kb-personal-study",
    knowledgeBaseName: "规程学习摘录库",
    categoryPath: ["我的空间", "学习摘录"],
    professionalType: "AGC 考核",
    tags: ["题库", "自测"],
    metadata: { source: "题库整理", subject: "AGC 考核", progress: "待复习" },
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderId: "u-run-admin",
    uploaderName: "张工",
    updatedAt: "2026-07-02 19:05",
    createdAt: "2026-07-02 19:05",
    size: "244KB",
    summary: "AGC 考核常见题型与易错点整理，用于班组自测复习。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: false,
  },
  // ── 智能对话引用资料（与 chat DOCS 一一对应，可在文件总览打开）──
  {
    id: "file-chat-agc-clause",
    name: "《并网发电厂辅助服务管理实施细则》AGC 考核条款解读.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["AGC", "考核", "两细则"],
    metadata: { docType: "规程制度", period: "通用", topic: "考核指标", docNo: "AGC-CHAT-001" },
    fullTextContent:
      "AGC 调节速率 调节精度 响应时间 三项指标综合考核 K值法 厂站侧执行要点 辅助服务管理实施细则",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2024-09-12 10:00",
    createdAt: "2024-09-01 09:00",
    size: "1.2MB",
    summary: "解读 AGC 考核三项指标、补偿计算方法与厂站侧执行要点，供智能对话溯源引用。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-chat-agc-sop",
    name: "厂家 SOP：AGC 控制器死区与速率配置说明.docx",
    type: "docx",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    categoryPath: ["运行专业", "交易与考核"],
    professionalType: "AGC",
    tags: ["AGC", "死区", "SOP"],
    metadata: { docType: "操作手册", period: "通用", topic: "控制参数", docNo: "AGC-SOP-001" },
    fullTextContent: "AGC 控制器 死区 推荐 ≤1MW 速率限制 爬坡能力 调度同意",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2024-06-20 14:30",
    createdAt: "2024-06-10 11:00",
    size: "486KB",
    summary: "厂家 AGC 控制器死区与速率限幅配置说明，对话引用中的 SOP 原文来源。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-chat-transformer-outage",
    name: "500kV 主变停役标准化操作程序 v3.2.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["主变", "停役", "操作程序"],
    metadata: { docType: "操作票", segment: "启停操作", voltage: "500kV", docNo: "OP-500-032" },
    fullTextContent:
      "500kV 主变停役 前置核对 负荷转移 保护连接片 中性点接地 操作步骤 风险与禁忌 恢复送电",
    version: "v3.2",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2024-08-03 09:20",
    createdAt: "2024-07-15 08:00",
    size: "1.85MB",
    summary: "500kV 主变停役前置核对、操作步骤与风险禁忌，智能对话主变停役问答的依据原文。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
    favorite: true,
  },
  {
    id: "file-chat-plant-ops-rule",
    name: "厂站运行规程(华东 A 厂)2024 修订版 摘要.docx",
    type: "docx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["厂站资料", "运行规程"],
    metadata: { docType: "运行规程", segment: "启停操作", voltage: "全厂", docNo: "PLANT-A-2024" },
    fullTextContent: "厂站运行规程 总则 值班巡检 异常处置 厂站资料优先适用 通用规程作为补充",
    version: "v2024",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2024-07-01 10:00",
    createdAt: "2024-06-20 09:00",
    size: "920KB",
    summary: "华东 A 厂运行规程摘要，规定值班、巡检与异常处置原则。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-chat-bus-diff-misop",
    name: "某 500kV 站母差保护误动事故复盘报告.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["母差", "误动", "复盘"],
    metadata: { docType: "复盘记录", segment: "继电保护", voltage: "500kV", docNo: "CASE-BUS-2023" },
    fullTextContent: "母差保护误动 TA二次回路绝缘破损 差动平衡 事件经过 原因分析 培训复习",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2023-11-08 16:40",
    createdAt: "2023-11-01 09:00",
    size: "2.1MB",
    summary: "500kV 站母差误动事故复盘，聚焦 TA 二次回路绝缘与验收管理根因。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-chat-relay-inspection",
    name: "发电厂继电保护及安全自动装置检验规程.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["继电保护", "检验", "规程"],
    metadata: { docType: "运行规程", segment: "继电保护", voltage: "全厂", docNo: "RELAY-STD-995" },
    fullTextContent: "继电保护检验种类 周期 互感器 二次回路 现场检验 差动保护配置原则",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "李工",
    updatedAt: "2024-01-15 11:00",
    createdAt: "2023-12-01 09:00",
    size: "3.4MB",
    summary: "规定继电保护检验种类、周期与现场检验要求，覆盖互感器与二次回路。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-chat-diff-review",
    name: "差动保护动作复盘：核查思路与典型场景.pdf",
    type: "pdf",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["差动", "复盘", "核查"],
    metadata: { docType: "作业指导书", segment: "继电保护", voltage: "全厂", docNo: "DIFF-REVIEW-01" },
    fullTextContent: "差动保护动作 四步法核查 TA极性 二次回路 定值 一次设备",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "张工",
    updatedAt: "2024-04-18 15:20",
    createdAt: "2024-04-01 09:00",
    size: "780KB",
    summary: "差动保护动作后按 TA 极性→二次回路→定值→一次设备四步法核查。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
  {
    id: "file-chat-bus-misoperation",
    name: "某厂母线倒闸操作误送电事故复盘.pptx",
    type: "pptx",
    knowledgeBaseId: "kb-grid-operation",
    knowledgeBaseName: "并网运行管理库",
    categoryPath: ["运行专业", "规程制度"],
    professionalType: "运行",
    tags: ["母线倒闸", "误送电", "复盘"],
    metadata: { docType: "复盘记录", segment: "启停操作", voltage: "220kV", docNo: "CASE-BUS-TX-2022" },
    fullTextContent: "母线倒闸 误送电 非同期 操作票漏写 母联三相位置核对 监护流于形式",
    version: "v1",
    isCurrentVersion: true,
    status: "published",
    parseStatus: "success",
    uploaderName: "王工",
    updatedAt: "2022-12-08 14:00",
    createdAt: "2022-12-01 09:00",
    size: "4.2MB",
    summary: "母线倒闸误送电事故复盘，强调母联三相位置核对与操作票模板评审。",
    canPreview: true,
    canDownload: true,
    canEdit: true,
  },
];

export const PERSONAL_DIRECTORIES: PersonalDirectory[] = [
  { id: "personal-root", name: "个人目录" },
  { id: "personal-work", parentId: "personal-root", name: "工作笔记" },
  { id: "personal-study", parentId: "personal-root", name: "学习摘录" },
];

export const RECENT_FILE_IDS = [
  "file-chat-transformer-outage",
  "file-chat-agc-clause",
  "file-grid-guide",
  "file-agc-rule",
  "file-personal-shift-log",
  "file-chat-agc-sop",
  "file-grid-ticket",
  "file-agc-report",
  "file-personal-trip-review",
  "file-chat-plant-ops-rule",
  "file-grid-blackstart",
  "file-agc-monthly-may",
  "file-personal-note",
  "file-chat-bus-diff-misop",
  "file-grid-freq-control",
  "file-agc-kpi-manual",
  "file-public-safety",
  "file-chat-relay-inspection",
  "file-grid-voltage",
  "file-agc-template",
  "file-chat-diff-review",
  "file-grid-line-outage",
  "file-agc-case",
  "file-personal-agc-quiz",
  "file-chat-bus-misoperation",
  "file-grid-relay-check",
  "file-agc-test",
  "file-grid-tie-line",
  "file-spot-rule",
  "file-grid-unit-start",
];

export const FAVORITE_FILE_IDS = [
  "file-chat-transformer-outage",
  "file-chat-agc-clause",
  "file-grid-guide",
  "file-personal-trip-review",
  "file-personal-grid-excerpt",
];

export const UPLOAD_RECORDS: UploadRecord[] = [
  {
    id: "upload-contract",
    fileId: "file-contract",
    fileName: "中长期合同签订规程.pdf",
    targetKnowledgeBaseId: "kb-trading-standard",
    targetKnowledgeBaseName: "电力交易业务技术标准库",
    submittedAt: "2026-07-07 13:08",
    updatedAt: "2026-07-07 13:08",
    status: "pendingApproval",
    parseStatus: "success",
    docParseStatus: "success",
    aiParseStatus: "success",
    reviewNote: "解析已完成，等待管理员审核",
    parseStartedAt: "2026-07-07 13:10",
    parseUpdatedAt: "2026-07-07 13:25",
    parseResult: "共 42 个分块 · 28 页 · 耗时 1分15秒",
  },
  {
    id: "upload-personal-note",
    fileId: "file-personal-note",
    fileName: "个人学习笔记汇总.docx",
    targetKnowledgeBaseId: "kb-personal-work",
    targetKnowledgeBaseName: "运行值班笔记库",
    submittedAt: "2026-07-07 19:10",
    updatedAt: "2026-07-07 19:28",
    status: "pendingConfirm",
    parseStatus: "success",
    docParseStatus: "success",
    aiParseStatus: "success",
    reviewNote: "解析已完成，等待本人在文件确认中核对",
    parseStartedAt: "2026-07-07 19:12",
    parseUpdatedAt: "2026-07-07 19:28",
    parseResult: "共 36 个分块 · 18 页 · 耗时 1分05秒",
  },
  {
    id: "upload-agc-report",
    fileId: "file-agc-rule",
    fileName: "AGC 考核标准细则.pdf",
    targetKnowledgeBaseId: "kb-agc",
    targetKnowledgeBaseName: "AGC 考核标准库",
    submittedAt: "2026-07-06 09:42",
    updatedAt: "2026-07-06 10:28",
    status: "published",
    parseStatus: "success",
    reviewerName: "李工",
    reviewedAt: "2026-07-06 09:58",
    reviewNote: "资料完整，符合入库要求",
    parseStartedAt: "2026-07-06 10:00",
    parseUpdatedAt: "2026-07-06 10:18",
    parseResult: "共 128 个分块 · 80 页 · 耗时 2分18秒",
    version: "V1.0",
    publishedAt: "2026-07-06 10:28",
    publisherName: "王管理",
  },
  {
    id: "upload-market-note",
    fileId: "file-personal-market-note",
    fileName: "现货报价策略备忘.xlsx",
    targetKnowledgeBaseId: "kb-personal-work",
    targetKnowledgeBaseName: "运行值班笔记库",
    submittedAt: "2026-07-07 10:15",
    updatedAt: "2026-07-07 10:26",
    status: "parsing",
    parseStatus: "parsing",
    docParseStatus: "success",
    aiParseStatus: "parsing",
    reviewerName: "系统",
    reviewedAt: "2026-07-07 10:15",
    reviewNote: "个人库上传，解析完成后进入文件确认",
    parseStartedAt: "2026-07-07 10:18",
    parseUpdatedAt: "2026-07-07 10:26",
    parseProgress: 72,
  },
  {
    id: "upload-rejected",
    fileId: "file-public-safety",
    fileName: "典型经验汇编.pdf",
    targetKnowledgeBaseId: "kb-public-regulation",
    targetKnowledgeBaseName: "规章制度汇编库",
    submittedAt: "2026-07-02 08:10",
    updatedAt: "2026-07-02 09:05",
    status: "rejected",
    parseStatus: "waiting",
    rejectReason: "资料来源和审批依据不完整，请补充后重新提交。",
    reviewerName: "李工",
    reviewedAt: "2026-07-02 09:05",
    reviewNote: "资料来源和审批依据不完整，请补充后重新提交。",
  },
  {
    id: "upload-parse-failed",
    fileId: "file-grid-parse-failed",
    fileName: "并网异常处置复盘扫描件.pdf",
    targetKnowledgeBaseId: "kb-grid-operation",
    targetKnowledgeBaseName: "并网运行管理库",
    submittedAt: "2026-07-05 14:20",
    updatedAt: "2026-07-05 14:41",
    status: "parseFailed",
    parseStatus: "failed",
    parseError: "扫描件文字层缺失，OCR 识别失败",
    reviewerName: "赵工",
    reviewedAt: "2026-07-05 14:30",
    reviewNote: "审核通过，等待文件解析",
    parseStartedAt: "2026-07-05 14:33",
    parseUpdatedAt: "2026-07-05 14:41",
  },
  {
    id: "upload-personal-draft",
    fileId: "file-personal-draft",
    fileName: "AGC 指标复盘草稿.docx",
    targetKnowledgeBaseId: "kb-personal-work",
    targetKnowledgeBaseName: "运行值班笔记库",
    submittedAt: "2026-07-05 20:16",
    updatedAt: "2026-07-05 20:40",
    status: "pendingConfirm",
    parseStatus: "success",
    docParseStatus: "success",
    aiParseStatus: "success",
    reviewNote: "解析已完成，等待本人在文件确认中核对",
    parseStartedAt: "2026-07-05 20:18",
    parseUpdatedAt: "2026-07-05 20:40",
    parseResult: "共 22 个分块 · 12 页 · 耗时 48秒",
  },
  {
    id: "upload-disabled",
    fileId: "file-agc-test",
    fileName: "AGC 性能试验导则.pdf",
    targetKnowledgeBaseId: "kb-agc",
    targetKnowledgeBaseName: "AGC 考核标准库",
    submittedAt: "2026-05-30 16:00",
    updatedAt: "2026-07-01 11:20",
    status: "disabled",
    parseStatus: "success",
    reviewerName: "李工",
    reviewedAt: "2026-05-30 16:20",
    reviewNote: "审核通过",
    parseStartedAt: "2026-05-30 16:22",
    parseUpdatedAt: "2026-05-30 16:40",
    parseResult: "共 86 个分块 · 52 页",
    version: "V2.0",
    publishedAt: "2026-05-30 17:00",
    publisherName: "王管理",
    disabledReason: "标准已升版，原文件停用，请上传新版本。",
  },
];

/** 个人库「文件确认」队列，与审批台 UPLOAD_APPROVALS 解耦 */
export const FILE_CONFIRMS: UploadApproval[] = [
  {
    id: "confirm-personal-note",
    fileName: "个人学习笔记汇总.docx",
    knowledgeBaseName: "运行值班笔记库",
    knowledgeBaseId: "kb-personal-work",
    submitterName: "张工",
    submittedAt: "2026-07-07 19:10",
    fileSize: "856KB",
    uploadNote: "个人库上传，待本人确认 AI 解析内容",
    status: "pendingApproval",
    parseStatus: "success",
    summary: "个人学习笔记、规程摘录与待整理问题清单。",
    aiKeywords: ["学习笔记", "运行规程", "待整理"],
    aiMetadata: [
      { id: "meta-note-type", label: "笔记类型", value: "学习摘录" },
      { id: "meta-note-topic", label: "主题", value: "运行监视" },
      { id: "meta-note-shift", label: "班次", value: "不涉及" },
    ],
    aiQuestions: ["笔记中待整理的重点问题有哪些？", "摘录的规程要点如何归档？"],
    aiAnswers: [
      "重点包括交接班遗留事项、异常工况处置口径与待核对指标。",
      "按主题标签整理后放入对应个人知识库分类。",
    ],
    aiExercises: [
      {
        id: "exercise-note-single",
        type: "single",
        stem: "个人库文件确认阶段，主要核对的是？",
        options: [
          { id: "A", label: "A", content: "管理员审批意见" },
          { id: "B", label: "B", content: "AI 解析内容是否准确" },
          { id: "C", label: "C", content: "跨库移动目标" },
          { id: "D", label: "D", content: "权限申请理由" },
        ],
        correctAnswers: ["B"],
        analysis: "个人库上传由本人在文件确认中核对 AI 解析内容，不进入审批台。",
      },
    ],
  },
  {
    id: "confirm-personal-draft",
    fileName: "AGC 指标复盘草稿.docx",
    knowledgeBaseName: "运行值班笔记库",
    knowledgeBaseId: "kb-personal-work",
    submitterName: "张工",
    submittedAt: "2026-07-05 20:16",
    fileSize: "420KB",
    uploadNote: "个人整理草稿，确认后发布到个人库",
    status: "pendingApproval",
    parseStatus: "success",
    summary: "个人整理的 AGC 指标复盘草稿，可提交到公共知识库。",
    aiKeywords: ["AGC", "指标复盘", "草稿"],
    aiMetadata: [
      { id: "meta-draft-type", label: "笔记类型", value: "草稿" },
      { id: "meta-draft-topic", label: "主题", value: "AGC" },
    ],
    aiQuestions: ["AGC 指标复盘应关注哪些维度？"],
    aiAnswers: ["可从调节性能、考核边界与异常样本三个维度整理。"],
    aiExercises: [],
  },
];

/** 审批台「文件移动列表」：个人库移入公共/专业库，待管理员批准移入 */
export const FILE_MOVE_APPROVALS: FileMoveApproval[] = [
  {
    id: "move-trip-review",
    fileId: "file-personal-trip-review",
    fileName: "主变跳闸复盘纪要.docx",
    sourceKnowledgeBaseId: "kb-personal-work",
    sourceKnowledgeBaseName: "运行值班笔记库",
    targetKnowledgeBaseId: "kb-grid-operation",
    targetKnowledgeBaseName: "并网运行管理库",
    submitterName: "张工",
    submittedAt: "2026-07-07 15:20",
    fileSize: "528KB",
    status: "pendingMove",
  },
  {
    id: "move-agc-quiz",
    fileId: "file-personal-agc-quiz",
    fileName: "AGC 考核题库整理.xlsx",
    sourceKnowledgeBaseId: "kb-personal-study",
    sourceKnowledgeBaseName: "规程学习摘录库",
    targetKnowledgeBaseId: "kb-agc",
    targetKnowledgeBaseName: "AGC 考核标准库",
    submitterName: "张工",
    submittedAt: "2026-07-07 14:05",
    fileSize: "244KB",
    status: "pendingMove",
  },
];

export const UPLOAD_APPROVALS: UploadApproval[] = [
  {
    id: "approval-contract",
    fileName: "中长期合同签订规程.pdf",
    knowledgeBaseName: "电力交易业务技术标准库",
    knowledgeBaseId: "kb-grid-trade",
    submitterName: "张工",
    submittedAt: "2026-07-07 13:08",
    fileSize: "2.4 MB",
    uploadNote: "补充交易执行口径说明",
    riskHint: "同名文件，建议作为新版本上传",
    status: "pendingApproval",
    parseStatus: "success",
    uploadType: "direct",
    contentConfirmStatus: "unconfirmed",
    summary: "本规程明确中长期合同签订流程、审批节点与执行边界。",
    aiKeywords: ["合同签订", "审批流程", "交易执行"],
    aiMetadata: [
      { id: "meta-contract-type", label: "文档类型", value: "管理规程" },
      { id: "meta-contract-year", label: "适用年度", value: "2026" },
      { id: "meta-contract-scope", label: "适用范围", value: "中长期电力交易" },
    ],
    aiQuestions: ["合同签订需要哪些审批节点？", "合同执行发生偏差时应如何处理？"],
    aiAnswers: [
      "依次完成业务复核、风险校验与授权审批后方可签订。",
      "应记录偏差原因，按合同约定发起变更或结算调整流程。",
    ],
    aiExercises: [
      {
        id: "exercise-contract-single",
        type: "single",
        stem: "中长期合同正式签订前，最后一个必须完成的环节是？",
        options: [
          { id: "A", label: "A", content: "业务复核" },
          { id: "B", label: "B", content: "风险校验" },
          { id: "C", label: "C", content: "授权审批" },
          { id: "D", label: "D", content: "月度结算" },
        ],
        correctAnswers: ["C"],
        analysis: "规程要求依次完成业务复核、风险校验和授权审批，授权审批是合同签订前的最后环节。",
      },
      {
        id: "exercise-contract-multiple",
        type: "multiple",
        stem: "合同执行发生偏差时，需要留存和处理的信息包括哪些？",
        options: [
          { id: "A", label: "A", content: "偏差原因" },
          { id: "B", label: "B", content: "变更记录" },
          { id: "C", label: "C", content: "结算调整依据" },
          { id: "D", label: "D", content: "无关市场传闻" },
        ],
        correctAnswers: ["A", "B", "C"],
        analysis: "偏差处理需要形成完整业务证据链，市场传闻不属于合同执行依据。",
      },
      {
        id: "exercise-contract-judge",
        type: "judge",
        stem: "合同执行发生偏差后，可以不记录原因直接调整结算结果。",
        options: [
          { id: "A", label: "A", content: "正确" },
          { id: "B", label: "B", content: "错误" },
        ],
        correctAnswers: ["B"],
        analysis: "错误。应先记录偏差原因，并按合同约定发起变更或结算调整流程。",
      },
    ],
    categoryId: "cat-run-market",
  },
  {
    id: "approval-grid-training",
    fileName: "并网运行异常处置培训手册.pdf",
    knowledgeBaseName: "并网运行管理库",
    knowledgeBaseId: "kb-grid-operation",
    submitterName: "陈工",
    submittedAt: "2026-07-07 11:42",
    fileSize: "3.1 MB",
    uploadNote: "补充现场异常处置培训材料",
    status: "pendingApproval",
    parseStatus: "success",
    uploadType: "direct",
    contentConfirmStatus: "unconfirmed",
    summary: "手册覆盖并网运行异常识别、现场上报、协同处置与复盘要求。",
    aiKeywords: ["并网运行", "异常处置", "现场上报", "复盘"],
    aiMetadata: [
      { id: "meta-grid-type", label: "文档类型", value: "培训手册" },
      { id: "meta-grid-level", label: "适用岗位", value: "运行值班员" },
      { id: "meta-grid-version", label: "版本", value: "V1.2" },
    ],
    aiQuestions: ["发现并网运行异常后的首要动作是什么？"],
    aiAnswers: ["先确认告警与设备状态，立即按分级要求上报并保留现场记录。"],
    aiExercises: [
      {
        id: "exercise-grid-single",
        type: "single",
        stem: "发现并网运行异常后的首要动作是什么？",
        options: [
          { id: "A", label: "A", content: "立即退出运行" },
          { id: "B", label: "B", content: "确认告警与设备状态" },
          { id: "C", label: "C", content: "等待下一班处理" },
          { id: "D", label: "D", content: "删除告警记录" },
        ],
        correctAnswers: ["B"],
        analysis: "异常处置首先需要确认告警真实性和设备状态，再按分级要求上报。",
      },
      {
        id: "exercise-grid-multiple",
        type: "multiple",
        stem: "并网运行异常处置中，需要同步完成哪些工作？",
        options: [
          { id: "A", label: "A", content: "确认告警与设备状态" },
          { id: "B", label: "B", content: "按分级要求上报" },
          { id: "C", label: "C", content: "保留现场记录" },
          { id: "D", label: "D", content: "删除异常告警" },
        ],
        correctAnswers: ["A", "B", "C"],
        analysis: "异常处置应完成状态确认、分级上报和现场留痕，不能删除告警记录。",
      },
      {
        id: "exercise-grid-judge",
        type: "judge",
        stem: "现场异常记录应保留至复盘完成。",
        options: [
          { id: "A", label: "A", content: "正确" },
          { id: "B", label: "B", content: "错误" },
        ],
        correctAnswers: ["A"],
        analysis: "正确。现场记录是异常分析、责任确认和后续复盘的重要依据。",
      },
    ],
    categoryId: "cat-run-grid",
  },
  {
    id: "approval-agc-checklist",
    fileName: "AGC 月度考核复核清单.xlsx",
    knowledgeBaseName: "AGC 考核标准库",
    knowledgeBaseId: "kb-agc",
    submitterName: "李工",
    submittedAt: "2026-07-07 10:36",
    fileSize: "428 KB",
    uploadNote: "新增月度复核字段与责任人说明",
    status: "pendingApproval",
    parseStatus: "success",
    uploadType: "direct",
    contentConfirmStatus: "unconfirmed",
    summary: "清单用于核对 AGC 月度考核数据、异常项与责任人确认结果。",
    aiKeywords: ["AGC", "月度考核", "复核清单"],
    aiMetadata: [
      { id: "meta-agc-type", label: "文档类型", value: "业务清单" },
      { id: "meta-agc-cycle", label: "统计周期", value: "月度" },
      { id: "meta-agc-owner", label: "责任专业", value: "运行专业" },
    ],
    aiQuestions: ["月度复核时需要重点确认哪些数据？"],
    aiAnswers: ["重点确认考核时段、指令执行偏差、免考依据及责任人签认信息。"],
    aiExercises: [
      {
        id: "exercise-agc-multiple",
        type: "multiple",
        stem: "AGC 月度复核需要重点确认哪些信息？",
        options: [
          { id: "A", label: "A", content: "考核时段" },
          { id: "B", label: "B", content: "指令执行偏差" },
          { id: "C", label: "C", content: "免考依据" },
          { id: "D", label: "D", content: "责任人签认" },
        ],
        correctAnswers: ["A", "B", "C", "D"],
        analysis: "四项信息共同构成月度复核的完整核验范围。",
      },
      {
        id: "exercise-agc-judge",
        type: "judge",
        stem: "复核清单中的异常项不需要责任人签认。",
        options: [
          { id: "A", label: "A", content: "正确" },
          { id: "B", label: "B", content: "错误" },
        ],
        correctAnswers: ["B"],
        analysis: "错误。异常项必须完成责任人确认，保证复核过程可追溯。",
      },
    ],
    categoryId: "cat-run-agc",
  },
  {
    id: "approval-agc-report",
    fileName: "AGC 指标月报补充说明.docx",
    knowledgeBaseName: "AGC 考核标准库",
    knowledgeBaseId: "kb-agc",
    submitterName: "李工",
    submittedAt: "2026-07-07 09:28",
    fileSize: "856 KB",
    uploadNote: "月度统计方法更新",
    status: "approved",
    parseStatus: "success",
    uploadType: "direct",
    contentConfirmStatus: "confirmed",
    reviewedAt: "2026-07-07 10:05",
    reviewerName: "张工",
  },
  {
    id: "approval-dispatch-rejected",
    fileName: "并网运行管理补充说明.docx",
    knowledgeBaseName: "并网运行管理库",
    knowledgeBaseId: "kb-grid-operation",
    submitterName: "陈工",
    submittedAt: "2026-07-06 16:40",
    fileSize: "1.3 MB",
    uploadNote: "补充联络线协同处置说明",
    status: "rejected",
    parseStatus: "success",
    uploadType: "direct",
    contentConfirmStatus: "unconfirmed",
    reviewedAt: "2026-07-07 09:12",
    reviewerName: "张工",
    reviewNote: "请补充适用范围与现场审批依据。",
  },
  {
    id: "approval-equipment-approved",
    fileName: "设备技术标准修订稿.pdf",
    knowledgeBaseName: "设备技术标准库",
    knowledgeBaseId: "kb-equipment-standard",
    submitterName: "王工",
    submittedAt: "2026-07-05 14:20",
    fileSize: "2.8 MB",
    uploadNote: "设备检修标准年度修订",
    status: "approved",
    parseStatus: "success",
    uploadType: "direct",
    contentConfirmStatus: "confirmed",
    reviewedAt: "2026-07-06 11:08",
    reviewerName: "张工",
    reviewNote: "内容完整，已通过审核。",
  },
  {
    id: "approval-move-grid-excerpt",
    fileId: "file-personal-grid-excerpt",
    fileName: "并网管理规程重点摘录.pdf",
    knowledgeBaseName: "并网运行管理库",
    knowledgeBaseId: "kb-grid-operation",
    submitterName: "张工",
    submittedAt: "2026-07-07 12:30",
    fileSize: "1.12MB",
    uploadNote: "个人库移入，已批准移入并完成重解析，待内容确认",
    status: "pendingApproval",
    parseStatus: "success",
    uploadType: "move",
    contentConfirmStatus: "unconfirmed",
    summary: "从个人学习库移入的并网管理规程重点摘录，含运行值班相关条款。",
    aiKeywords: ["并网管理", "规程摘录", "运行值班"],
    aiMetadata: [
      { id: "meta-move-type", label: "文档类型", value: "规程摘录" },
      { id: "meta-move-source", label: "来源", value: "个人库移入" },
    ],
    aiQuestions: ["并网管理规程中与运行值班相关的重点有哪些？"],
    aiAnswers: ["重点包括启停机条件、异常上报路径与值班交接注意事项。"],
    aiExercises: [],
    categoryId: "cat-run-grid",
  },
];

export const PERMISSION_REQUESTS: PermissionRequest[] = [
  {
    id: "perm-agc",
    applicantName: "王工",
    knowledgeBaseId: "kb-agc",
    knowledgeBaseName: "AGC 考核标准库",
    group: "view",
    reason: "需查看调度规程",
    submittedAt: "07-08 10:20",
    notifyStatus: "waiting",
  },
  {
    id: "perm-equipment",
    applicantName: "张工",
    knowledgeBaseId: "kb-equipment-standard",
    knowledgeBaseName: "设备技术标准库",
    group: "view",
    reason: "需要查阅主设备试验标准，用于并网异常复盘。",
    submittedAt: "2026-07-07 11:30",
    notifyStatus: "waiting",
  },
  {
    id: "perm-dispatch",
    applicantName: "陈工",
    knowledgeBaseId: "kb-dispatch-rule",
    knowledgeBaseName: "调度运行规程库",
    group: "upload",
    reason: "补充联络线协调记录模板。",
    submittedAt: "2026-07-06 16:40",
    notifyStatus: "sent",
  },
];

export const PERMISSION_MEMBERS: Record<string, PermissionMember[]> = {
  "kb-grid-operation": [
    { id: "u-run-admin", name: "张工", group: "manage" },
    { id: "u-li", name: "李工", group: "upload" },
  ],
  "kb-agc": [
    { id: "u-run-admin", name: "张工", group: "manage" },
    { id: "u-chen", name: "陈工", group: "view" },
  ],
};

export const PARSE_EXCEPTIONS: ParseException[] = [
  {
    id: "parse-grid-scan",
    fileId: "file-grid-parse-failed",
    fileName: "并网异常处置复盘扫描件.pdf",
    knowledgeBaseName: "并网运行管理库",
    uploadedAt: "2026-07-07 08:40",
    reason: "扫描件文字层缺失，OCR 识别失败",
    uploaderName: "陈工",
    fileSize: "4.2 MB",
    version: "v1",
  },
  {
    id: "parse-agc-upload",
    fileId: "file-agc-report",
    fileName: "AGC 指标统计附件.xlsx",
    knowledgeBaseName: "AGC 考核标准库",
    uploadedAt: "2026-07-07 10:12",
    reason: "工作表合并单元格过多，解析任务超时",
    uploaderName: "李工",
    fileSize: "1.1 MB",
    version: "v2",
  },
  {
    id: "parse-personal-note",
    fileId: "file-personal-scan",
    fileName: "值班笔记扫描件.jpg",
    knowledgeBaseName: "运行值班笔记库",
    uploadedAt: "2026-07-06 22:15",
    reason: "图片分辨率过低，文档解析引擎无法提取有效文本",
    uploaderName: "张工",
    fileSize: "820 KB",
    version: "v1",
  },
];
