/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SceneRouteImport } from './routes/scene'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as LearnAdminRouteImport } from './routes/learn-admin'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ExamAdminRouteImport } from './routes/exam-admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as ScenarioIndexRouteImport } from './routes/scenario.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnAdminIndexRouteImport } from './routes/learn-admin.index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as ExamAdminIndexRouteImport } from './routes/exam-admin.index'
import { Route as TrainingWrongRouteImport } from './routes/training.wrong'
import { Route as TrainingRecordsRouteImport } from './routes/training.records'
import { Route as TrainingPracticeRouteImport } from './routes/training.practice'
import { Route as TrainingGrowthRouteImport } from './routes/training.growth'
import { Route as TrainingExamRouteImport } from './routes/training.exam'
import { Route as ScenarioPeakRouteImport } from './routes/scenario.peak'
import { Route as ScenarioFaultRouteImport } from './routes/scenario.fault'
import { Route as KnowledgeMineRouteImport } from './routes/knowledge.mine'
import { Route as KnowledgeAllRouteImport } from './routes/knowledge.all'
import { Route as KnowledgeAdminRouteImport } from './routes/knowledge.admin'
import { Route as ScenarioTypicalIndexRouteImport } from './routes/scenario.typical.index'
import { Route as ScenarioFaultIndexRouteImport } from './routes/scenario.fault.index'
import { Route as TrainingSessionIdRouteImport } from './routes/training.session.$id'
import { Route as TrainingResultIdRouteImport } from './routes/training.result.$id'
import { Route as LearnTopicIdRouteImport } from './routes/learn.topic.$id'
import { Route as LearnDocIdRouteImport } from './routes/learn.doc.$id'
import { Route as LearnAdminTopicNewRouteImport } from './routes/learn-admin.topic.new'
import { Route as KnowledgeSpacePublicRouteImport } from './routes/knowledge.space.public'
import { Route as KnowledgeLibLibIdRouteImport } from './routes/knowledge.lib.$libId'
import { Route as KnowledgeKbKbIdRouteImport } from './routes/knowledge.kb.$kbId'
import { Route as KnowledgeFileFileIdRouteImport } from './routes/knowledge.file.$fileId'
import { Route as KnowledgeDeptDeptIdRouteImport } from './routes/knowledge.dept.$deptId'
import { Route as ExamAdminPaperNewRouteImport } from './routes/exam-admin.paper.new'
import { Route as AssetsCollectionIdRouteImport } from './routes/assets.collection.$id'
import { Route as ScenarioTypicalResultIdRouteImport } from './routes/scenario.typical.result.$id'
import { Route as ScenarioSootblowResultIdRouteImport } from './routes/scenario.sootblow.result.$id'
import { Route as ScenarioPeakResultIdRouteImport } from './routes/scenario.peak.result.$id'
import { Route as ScenarioFaultResultIdRouteImport } from './routes/scenario.fault.result.$id'
import { Route as LearnAdminTopicTopicIdEditRouteImport } from './routes/learn-admin.topic.$topicId.edit'
import { Route as KnowledgeSpaceDepartmentDepartmentIdRouteImport } from './routes/knowledge.space.department.$departmentId'
import { Route as ExamAdminPaperPaperIdPreviewRouteImport } from './routes/exam-admin.paper.$paperId.preview'
import { Route as ExamAdminPaperPaperIdEditRouteImport } from './routes/exam-admin.paper.$paperId.edit'
import { Route as KnowledgeKbKbIdFileFileIdRouteImport } from './routes/knowledge.kb.$kbId.file.$fileId'
import { Route as KnowledgeKbKbIdDirDirIdRouteImport } from './routes/knowledge.kb.$kbId.dir.$dirId'
import { Route as ExamAdminPaperPaperIdPersonPersonIdRouteImport } from './routes/exam-admin.paper.$paperId.person.$personId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneRoute = SceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAdminRoute = LearnAdminRouteImport.update({
  id: '/learn-admin',
  path: '/learn-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamAdminRoute = ExamAdminRouteImport.update({
  id: '/exam-admin',
  path: '/exam-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioIndexRoute = ScenarioIndexRouteImport.update({
  id: '/scenario/',
  path: '/scenario/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAdminIndexRoute = LearnAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnAdminRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ExamAdminIndexRoute = ExamAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamAdminRoute,
} as any)
const TrainingWrongRoute = TrainingWrongRouteImport.update({
  id: '/training/wrong',
  path: '/training/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRecordsRoute = TrainingRecordsRouteImport.update({
  id: '/training/records',
  path: '/training/records',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingPracticeRoute = TrainingPracticeRouteImport.update({
  id: '/training/practice',
  path: '/training/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingGrowthRoute = TrainingGrowthRouteImport.update({
  id: '/training/growth',
  path: '/training/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingExamRoute = TrainingExamRouteImport.update({
  id: '/training/exam',
  path: '/training/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioPeakRoute = ScenarioPeakRouteImport.update({
  id: '/scenario/peak',
  path: '/scenario/peak',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioFaultRoute = ScenarioFaultRouteImport.update({
  id: '/scenario/fault',
  path: '/scenario/fault',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeMineRoute = KnowledgeMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeAllRoute = KnowledgeAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeAdminRoute = KnowledgeAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ScenarioTypicalIndexRoute = ScenarioTypicalIndexRouteImport.update({
  id: '/scenario/typical/',
  path: '/scenario/typical/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioFaultIndexRoute = ScenarioFaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScenarioFaultRoute,
} as any)
const TrainingSessionIdRoute = TrainingSessionIdRouteImport.update({
  id: '/training/session/$id',
  path: '/training/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingResultIdRoute = TrainingResultIdRouteImport.update({
  id: '/training/result/$id',
  path: '/training/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicIdRoute = LearnTopicIdRouteImport.update({
  id: '/learn/topic/$id',
  path: '/learn/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDocIdRoute = LearnDocIdRouteImport.update({
  id: '/learn/doc/$id',
  path: '/learn/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAdminTopicNewRoute = LearnAdminTopicNewRouteImport.update({
  id: '/topic/new',
  path: '/topic/new',
  getParentRoute: () => LearnAdminRoute,
} as any)
const KnowledgeSpacePublicRoute = KnowledgeSpacePublicRouteImport.update({
  id: '/space/public',
  path: '/space/public',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeLibLibIdRoute = KnowledgeLibLibIdRouteImport.update({
  id: '/lib/$libId',
  path: '/lib/$libId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeKbKbIdRoute = KnowledgeKbKbIdRouteImport.update({
  id: '/kb/$kbId',
  path: '/kb/$kbId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeFileFileIdRoute = KnowledgeFileFileIdRouteImport.update({
  id: '/file/$fileId',
  path: '/file/$fileId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeDeptDeptIdRoute = KnowledgeDeptDeptIdRouteImport.update({
  id: '/dept/$deptId',
  path: '/dept/$deptId',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ExamAdminPaperNewRoute = ExamAdminPaperNewRouteImport.update({
  id: '/paper/new',
  path: '/paper/new',
  getParentRoute: () => ExamAdminRoute,
} as any)
const AssetsCollectionIdRoute = AssetsCollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => AssetsRoute,
} as any)
const ScenarioTypicalResultIdRoute = ScenarioTypicalResultIdRouteImport.update({
  id: '/scenario/typical/result/$id',
  path: '/scenario/typical/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioSootblowResultIdRoute =
  ScenarioSootblowResultIdRouteImport.update({
    id: '/scenario/sootblow/result/$id',
    path: '/scenario/sootblow/result/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenarioPeakResultIdRoute = ScenarioPeakResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => ScenarioPeakRoute,
} as any)
const ScenarioFaultResultIdRoute = ScenarioFaultResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => ScenarioFaultRoute,
} as any)
const LearnAdminTopicTopicIdEditRoute =
  LearnAdminTopicTopicIdEditRouteImport.update({
    id: '/topic/$topicId/edit',
    path: '/topic/$topicId/edit',
    getParentRoute: () => LearnAdminRoute,
  } as any)
const KnowledgeSpaceDepartmentDepartmentIdRoute =
  KnowledgeSpaceDepartmentDepartmentIdRouteImport.update({
    id: '/space/department/$departmentId',
    path: '/space/department/$departmentId',
    getParentRoute: () => KnowledgeRoute,
  } as any)
const ExamAdminPaperPaperIdPreviewRoute =
  ExamAdminPaperPaperIdPreviewRouteImport.update({
    id: '/paper/$paperId/preview',
    path: '/paper/$paperId/preview',
    getParentRoute: () => ExamAdminRoute,
  } as any)
const ExamAdminPaperPaperIdEditRoute =
  ExamAdminPaperPaperIdEditRouteImport.update({
    id: '/paper/$paperId/edit',
    path: '/paper/$paperId/edit',
    getParentRoute: () => ExamAdminRoute,
  } as any)
const KnowledgeKbKbIdFileFileIdRoute =
  KnowledgeKbKbIdFileFileIdRouteImport.update({
    id: '/file/$fileId',
    path: '/file/$fileId',
    getParentRoute: () => KnowledgeKbKbIdRoute,
  } as any)
const KnowledgeKbKbIdDirDirIdRoute = KnowledgeKbKbIdDirDirIdRouteImport.update({
  id: '/dir/$dirId',
  path: '/dir/$dirId',
  getParentRoute: () => KnowledgeKbKbIdRoute,
} as any)
const ExamAdminPaperPaperIdPersonPersonIdRoute =
  ExamAdminPaperPaperIdPersonPersonIdRouteImport.update({
    id: '/paper/$paperId/person/$personId',
    path: '/paper/$paperId/person/$personId',
    getParentRoute: () => ExamAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/chat': typeof ChatRoute
  '/exam-admin': typeof ExamAdminRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/learn-admin': typeof LearnAdminRouteWithChildren
  '/question-bank': typeof QuestionBankRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/knowledge/admin': typeof KnowledgeAdminRoute
  '/knowledge/all': typeof KnowledgeAllRoute
  '/knowledge/mine': typeof KnowledgeMineRoute
  '/scenario/fault': typeof ScenarioFaultRouteWithChildren
  '/scenario/peak': typeof ScenarioPeakRouteWithChildren
  '/training/exam': typeof TrainingExamRoute
  '/training/growth': typeof TrainingGrowthRoute
  '/training/practice': typeof TrainingPracticeRoute
  '/training/records': typeof TrainingRecordsRoute
  '/training/wrong': typeof TrainingWrongRoute
  '/exam-admin/': typeof ExamAdminIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/learn-admin/': typeof LearnAdminIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/scenario/': typeof ScenarioIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/assets/collection/$id': typeof AssetsCollectionIdRoute
  '/exam-admin/paper/new': typeof ExamAdminPaperNewRoute
  '/knowledge/dept/$deptId': typeof KnowledgeDeptDeptIdRoute
  '/knowledge/file/$fileId': typeof KnowledgeFileFileIdRoute
  '/knowledge/kb/$kbId': typeof KnowledgeKbKbIdRouteWithChildren
  '/knowledge/lib/$libId': typeof KnowledgeLibLibIdRoute
  '/knowledge/space/public': typeof KnowledgeSpacePublicRoute
  '/learn-admin/topic/new': typeof LearnAdminTopicNewRoute
  '/learn/doc/$id': typeof LearnDocIdRoute
  '/learn/topic/$id': typeof LearnTopicIdRoute
  '/training/result/$id': typeof TrainingResultIdRoute
  '/training/session/$id': typeof TrainingSessionIdRoute
  '/scenario/fault/': typeof ScenarioFaultIndexRoute
  '/scenario/typical/': typeof ScenarioTypicalIndexRoute
  '/exam-admin/paper/$paperId/edit': typeof ExamAdminPaperPaperIdEditRoute
  '/exam-admin/paper/$paperId/preview': typeof ExamAdminPaperPaperIdPreviewRoute
  '/knowledge/space/department/$departmentId': typeof KnowledgeSpaceDepartmentDepartmentIdRoute
  '/learn-admin/topic/$topicId/edit': typeof LearnAdminTopicTopicIdEditRoute
  '/scenario/fault/result/$id': typeof ScenarioFaultResultIdRoute
  '/scenario/peak/result/$id': typeof ScenarioPeakResultIdRoute
  '/scenario/sootblow/result/$id': typeof ScenarioSootblowResultIdRoute
  '/scenario/typical/result/$id': typeof ScenarioTypicalResultIdRoute
  '/exam-admin/paper/$paperId/person/$personId': typeof ExamAdminPaperPaperIdPersonPersonIdRoute
  '/knowledge/kb/$kbId/dir/$dirId': typeof KnowledgeKbKbIdDirDirIdRoute
  '/knowledge/kb/$kbId/file/$fileId': typeof KnowledgeKbKbIdFileFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/chat': typeof ChatRoute
  '/governance': typeof GovernanceRoute
  '/question-bank': typeof QuestionBankRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/knowledge/admin': typeof KnowledgeAdminRoute
  '/knowledge/all': typeof KnowledgeAllRoute
  '/knowledge/mine': typeof KnowledgeMineRoute
  '/scenario/peak': typeof ScenarioPeakRouteWithChildren
  '/training/exam': typeof TrainingExamRoute
  '/training/growth': typeof TrainingGrowthRoute
  '/training/practice': typeof TrainingPracticeRoute
  '/training/records': typeof TrainingRecordsRoute
  '/training/wrong': typeof TrainingWrongRoute
  '/exam-admin': typeof ExamAdminIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/learn-admin': typeof LearnAdminIndexRoute
  '/learn': typeof LearnIndexRoute
  '/scenario': typeof ScenarioIndexRoute
  '/training': typeof TrainingIndexRoute
  '/assets/collection/$id': typeof AssetsCollectionIdRoute
  '/exam-admin/paper/new': typeof ExamAdminPaperNewRoute
  '/knowledge/dept/$deptId': typeof KnowledgeDeptDeptIdRoute
  '/knowledge/file/$fileId': typeof KnowledgeFileFileIdRoute
  '/knowledge/kb/$kbId': typeof KnowledgeKbKbIdRouteWithChildren
  '/knowledge/lib/$libId': typeof KnowledgeLibLibIdRoute
  '/knowledge/space/public': typeof KnowledgeSpacePublicRoute
  '/learn-admin/topic/new': typeof LearnAdminTopicNewRoute
  '/learn/doc/$id': typeof LearnDocIdRoute
  '/learn/topic/$id': typeof LearnTopicIdRoute
  '/training/result/$id': typeof TrainingResultIdRoute
  '/training/session/$id': typeof TrainingSessionIdRoute
  '/scenario/fault': typeof ScenarioFaultIndexRoute
  '/scenario/typical': typeof ScenarioTypicalIndexRoute
  '/exam-admin/paper/$paperId/edit': typeof ExamAdminPaperPaperIdEditRoute
  '/exam-admin/paper/$paperId/preview': typeof ExamAdminPaperPaperIdPreviewRoute
  '/knowledge/space/department/$departmentId': typeof KnowledgeSpaceDepartmentDepartmentIdRoute
  '/learn-admin/topic/$topicId/edit': typeof LearnAdminTopicTopicIdEditRoute
  '/scenario/fault/result/$id': typeof ScenarioFaultResultIdRoute
  '/scenario/peak/result/$id': typeof ScenarioPeakResultIdRoute
  '/scenario/sootblow/result/$id': typeof ScenarioSootblowResultIdRoute
  '/scenario/typical/result/$id': typeof ScenarioTypicalResultIdRoute
  '/exam-admin/paper/$paperId/person/$personId': typeof ExamAdminPaperPaperIdPersonPersonIdRoute
  '/knowledge/kb/$kbId/dir/$dirId': typeof KnowledgeKbKbIdDirDirIdRoute
  '/knowledge/kb/$kbId/file/$fileId': typeof KnowledgeKbKbIdFileFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/chat': typeof ChatRoute
  '/exam-admin': typeof ExamAdminRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/learn-admin': typeof LearnAdminRouteWithChildren
  '/question-bank': typeof QuestionBankRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/knowledge/admin': typeof KnowledgeAdminRoute
  '/knowledge/all': typeof KnowledgeAllRoute
  '/knowledge/mine': typeof KnowledgeMineRoute
  '/scenario/fault': typeof ScenarioFaultRouteWithChildren
  '/scenario/peak': typeof ScenarioPeakRouteWithChildren
  '/training/exam': typeof TrainingExamRoute
  '/training/growth': typeof TrainingGrowthRoute
  '/training/practice': typeof TrainingPracticeRoute
  '/training/records': typeof TrainingRecordsRoute
  '/training/wrong': typeof TrainingWrongRoute
  '/exam-admin/': typeof ExamAdminIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/learn-admin/': typeof LearnAdminIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/scenario/': typeof ScenarioIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/assets/collection/$id': typeof AssetsCollectionIdRoute
  '/exam-admin/paper/new': typeof ExamAdminPaperNewRoute
  '/knowledge/dept/$deptId': typeof KnowledgeDeptDeptIdRoute
  '/knowledge/file/$fileId': typeof KnowledgeFileFileIdRoute
  '/knowledge/kb/$kbId': typeof KnowledgeKbKbIdRouteWithChildren
  '/knowledge/lib/$libId': typeof KnowledgeLibLibIdRoute
  '/knowledge/space/public': typeof KnowledgeSpacePublicRoute
  '/learn-admin/topic/new': typeof LearnAdminTopicNewRoute
  '/learn/doc/$id': typeof LearnDocIdRoute
  '/learn/topic/$id': typeof LearnTopicIdRoute
  '/training/result/$id': typeof TrainingResultIdRoute
  '/training/session/$id': typeof TrainingSessionIdRoute
  '/scenario/fault/': typeof ScenarioFaultIndexRoute
  '/scenario/typical/': typeof ScenarioTypicalIndexRoute
  '/exam-admin/paper/$paperId/edit': typeof ExamAdminPaperPaperIdEditRoute
  '/exam-admin/paper/$paperId/preview': typeof ExamAdminPaperPaperIdPreviewRoute
  '/knowledge/space/department/$departmentId': typeof KnowledgeSpaceDepartmentDepartmentIdRoute
  '/learn-admin/topic/$topicId/edit': typeof LearnAdminTopicTopicIdEditRoute
  '/scenario/fault/result/$id': typeof ScenarioFaultResultIdRoute
  '/scenario/peak/result/$id': typeof ScenarioPeakResultIdRoute
  '/scenario/sootblow/result/$id': typeof ScenarioSootblowResultIdRoute
  '/scenario/typical/result/$id': typeof ScenarioTypicalResultIdRoute
  '/exam-admin/paper/$paperId/person/$personId': typeof ExamAdminPaperPaperIdPersonPersonIdRoute
  '/knowledge/kb/$kbId/dir/$dirId': typeof KnowledgeKbKbIdDirDirIdRoute
  '/knowledge/kb/$kbId/file/$fileId': typeof KnowledgeKbKbIdFileFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/chat'
    | '/exam-admin'
    | '/governance'
    | '/knowledge'
    | '/learn-admin'
    | '/question-bank'
    | '/scene'
    | '/search'
    | '/knowledge/admin'
    | '/knowledge/all'
    | '/knowledge/mine'
    | '/scenario/fault'
    | '/scenario/peak'
    | '/training/exam'
    | '/training/growth'
    | '/training/practice'
    | '/training/records'
    | '/training/wrong'
    | '/exam-admin/'
    | '/knowledge/'
    | '/learn-admin/'
    | '/learn/'
    | '/scenario/'
    | '/training/'
    | '/assets/collection/$id'
    | '/exam-admin/paper/new'
    | '/knowledge/dept/$deptId'
    | '/knowledge/file/$fileId'
    | '/knowledge/kb/$kbId'
    | '/knowledge/lib/$libId'
    | '/knowledge/space/public'
    | '/learn-admin/topic/new'
    | '/learn/doc/$id'
    | '/learn/topic/$id'
    | '/training/result/$id'
    | '/training/session/$id'
    | '/scenario/fault/'
    | '/scenario/typical/'
    | '/exam-admin/paper/$paperId/edit'
    | '/exam-admin/paper/$paperId/preview'
    | '/knowledge/space/department/$departmentId'
    | '/learn-admin/topic/$topicId/edit'
    | '/scenario/fault/result/$id'
    | '/scenario/peak/result/$id'
    | '/scenario/sootblow/result/$id'
    | '/scenario/typical/result/$id'
    | '/exam-admin/paper/$paperId/person/$personId'
    | '/knowledge/kb/$kbId/dir/$dirId'
    | '/knowledge/kb/$kbId/file/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/chat'
    | '/governance'
    | '/question-bank'
    | '/scene'
    | '/search'
    | '/knowledge/admin'
    | '/knowledge/all'
    | '/knowledge/mine'
    | '/scenario/peak'
    | '/training/exam'
    | '/training/growth'
    | '/training/practice'
    | '/training/records'
    | '/training/wrong'
    | '/exam-admin'
    | '/knowledge'
    | '/learn-admin'
    | '/learn'
    | '/scenario'
    | '/training'
    | '/assets/collection/$id'
    | '/exam-admin/paper/new'
    | '/knowledge/dept/$deptId'
    | '/knowledge/file/$fileId'
    | '/knowledge/kb/$kbId'
    | '/knowledge/lib/$libId'
    | '/knowledge/space/public'
    | '/learn-admin/topic/new'
    | '/learn/doc/$id'
    | '/learn/topic/$id'
    | '/training/result/$id'
    | '/training/session/$id'
    | '/scenario/fault'
    | '/scenario/typical'
    | '/exam-admin/paper/$paperId/edit'
    | '/exam-admin/paper/$paperId/preview'
    | '/knowledge/space/department/$departmentId'
    | '/learn-admin/topic/$topicId/edit'
    | '/scenario/fault/result/$id'
    | '/scenario/peak/result/$id'
    | '/scenario/sootblow/result/$id'
    | '/scenario/typical/result/$id'
    | '/exam-admin/paper/$paperId/person/$personId'
    | '/knowledge/kb/$kbId/dir/$dirId'
    | '/knowledge/kb/$kbId/file/$fileId'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/chat'
    | '/exam-admin'
    | '/governance'
    | '/knowledge'
    | '/learn-admin'
    | '/question-bank'
    | '/scene'
    | '/search'
    | '/knowledge/admin'
    | '/knowledge/all'
    | '/knowledge/mine'
    | '/scenario/fault'
    | '/scenario/peak'
    | '/training/exam'
    | '/training/growth'
    | '/training/practice'
    | '/training/records'
    | '/training/wrong'
    | '/exam-admin/'
    | '/knowledge/'
    | '/learn-admin/'
    | '/learn/'
    | '/scenario/'
    | '/training/'
    | '/assets/collection/$id'
    | '/exam-admin/paper/new'
    | '/knowledge/dept/$deptId'
    | '/knowledge/file/$fileId'
    | '/knowledge/kb/$kbId'
    | '/knowledge/lib/$libId'
    | '/knowledge/space/public'
    | '/learn-admin/topic/new'
    | '/learn/doc/$id'
    | '/learn/topic/$id'
    | '/training/result/$id'
    | '/training/session/$id'
    | '/scenario/fault/'
    | '/scenario/typical/'
    | '/exam-admin/paper/$paperId/edit'
    | '/exam-admin/paper/$paperId/preview'
    | '/knowledge/space/department/$departmentId'
    | '/learn-admin/topic/$topicId/edit'
    | '/scenario/fault/result/$id'
    | '/scenario/peak/result/$id'
    | '/scenario/sootblow/result/$id'
    | '/scenario/typical/result/$id'
    | '/exam-admin/paper/$paperId/person/$personId'
    | '/knowledge/kb/$kbId/dir/$dirId'
    | '/knowledge/kb/$kbId/file/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  ChatRoute: typeof ChatRoute
  ExamAdminRoute: typeof ExamAdminRouteWithChildren
  GovernanceRoute: typeof GovernanceRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LearnAdminRoute: typeof LearnAdminRouteWithChildren
  QuestionBankRoute: typeof QuestionBankRoute
  SceneRoute: typeof SceneRoute
  SearchRoute: typeof SearchRoute
  ScenarioFaultRoute: typeof ScenarioFaultRouteWithChildren
  ScenarioPeakRoute: typeof ScenarioPeakRouteWithChildren
  TrainingExamRoute: typeof TrainingExamRoute
  TrainingGrowthRoute: typeof TrainingGrowthRoute
  TrainingPracticeRoute: typeof TrainingPracticeRoute
  TrainingRecordsRoute: typeof TrainingRecordsRoute
  TrainingWrongRoute: typeof TrainingWrongRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ScenarioIndexRoute: typeof ScenarioIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  LearnDocIdRoute: typeof LearnDocIdRoute
  LearnTopicIdRoute: typeof LearnTopicIdRoute
  TrainingResultIdRoute: typeof TrainingResultIdRoute
  TrainingSessionIdRoute: typeof TrainingSessionIdRoute
  ScenarioTypicalIndexRoute: typeof ScenarioTypicalIndexRoute
  ScenarioSootblowResultIdRoute: typeof ScenarioSootblowResultIdRoute
  ScenarioTypicalResultIdRoute: typeof ScenarioTypicalResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-admin': {
      id: '/learn-admin'
      path: '/learn-admin'
      fullPath: '/learn-admin'
      preLoaderRoute: typeof LearnAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-admin': {
      id: '/exam-admin'
      path: '/exam-admin'
      fullPath: '/exam-admin'
      preLoaderRoute: typeof ExamAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/': {
      id: '/scenario/'
      path: '/scenario'
      fullPath: '/scenario/'
      preLoaderRoute: typeof ScenarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-admin/': {
      id: '/learn-admin/'
      path: '/'
      fullPath: '/learn-admin/'
      preLoaderRoute: typeof LearnAdminIndexRouteImport
      parentRoute: typeof LearnAdminRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/exam-admin/': {
      id: '/exam-admin/'
      path: '/'
      fullPath: '/exam-admin/'
      preLoaderRoute: typeof ExamAdminIndexRouteImport
      parentRoute: typeof ExamAdminRoute
    }
    '/training/wrong': {
      id: '/training/wrong'
      path: '/training/wrong'
      fullPath: '/training/wrong'
      preLoaderRoute: typeof TrainingWrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/records': {
      id: '/training/records'
      path: '/training/records'
      fullPath: '/training/records'
      preLoaderRoute: typeof TrainingRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/practice': {
      id: '/training/practice'
      path: '/training/practice'
      fullPath: '/training/practice'
      preLoaderRoute: typeof TrainingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/growth': {
      id: '/training/growth'
      path: '/training/growth'
      fullPath: '/training/growth'
      preLoaderRoute: typeof TrainingGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/exam': {
      id: '/training/exam'
      path: '/training/exam'
      fullPath: '/training/exam'
      preLoaderRoute: typeof TrainingExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/peak': {
      id: '/scenario/peak'
      path: '/scenario/peak'
      fullPath: '/scenario/peak'
      preLoaderRoute: typeof ScenarioPeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/fault': {
      id: '/scenario/fault'
      path: '/scenario/fault'
      fullPath: '/scenario/fault'
      preLoaderRoute: typeof ScenarioFaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/mine': {
      id: '/knowledge/mine'
      path: '/mine'
      fullPath: '/knowledge/mine'
      preLoaderRoute: typeof KnowledgeMineRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/all': {
      id: '/knowledge/all'
      path: '/all'
      fullPath: '/knowledge/all'
      preLoaderRoute: typeof KnowledgeAllRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/admin': {
      id: '/knowledge/admin'
      path: '/admin'
      fullPath: '/knowledge/admin'
      preLoaderRoute: typeof KnowledgeAdminRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/scenario/typical/': {
      id: '/scenario/typical/'
      path: '/scenario/typical'
      fullPath: '/scenario/typical/'
      preLoaderRoute: typeof ScenarioTypicalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/fault/': {
      id: '/scenario/fault/'
      path: '/'
      fullPath: '/scenario/fault/'
      preLoaderRoute: typeof ScenarioFaultIndexRouteImport
      parentRoute: typeof ScenarioFaultRoute
    }
    '/training/session/$id': {
      id: '/training/session/$id'
      path: '/training/session/$id'
      fullPath: '/training/session/$id'
      preLoaderRoute: typeof TrainingSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/result/$id': {
      id: '/training/result/$id'
      path: '/training/result/$id'
      fullPath: '/training/result/$id'
      preLoaderRoute: typeof TrainingResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/topic/$id': {
      id: '/learn/topic/$id'
      path: '/learn/topic/$id'
      fullPath: '/learn/topic/$id'
      preLoaderRoute: typeof LearnTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/doc/$id': {
      id: '/learn/doc/$id'
      path: '/learn/doc/$id'
      fullPath: '/learn/doc/$id'
      preLoaderRoute: typeof LearnDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-admin/topic/new': {
      id: '/learn-admin/topic/new'
      path: '/topic/new'
      fullPath: '/learn-admin/topic/new'
      preLoaderRoute: typeof LearnAdminTopicNewRouteImport
      parentRoute: typeof LearnAdminRoute
    }
    '/knowledge/space/public': {
      id: '/knowledge/space/public'
      path: '/space/public'
      fullPath: '/knowledge/space/public'
      preLoaderRoute: typeof KnowledgeSpacePublicRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/lib/$libId': {
      id: '/knowledge/lib/$libId'
      path: '/lib/$libId'
      fullPath: '/knowledge/lib/$libId'
      preLoaderRoute: typeof KnowledgeLibLibIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/kb/$kbId': {
      id: '/knowledge/kb/$kbId'
      path: '/kb/$kbId'
      fullPath: '/knowledge/kb/$kbId'
      preLoaderRoute: typeof KnowledgeKbKbIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/file/$fileId': {
      id: '/knowledge/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/knowledge/file/$fileId'
      preLoaderRoute: typeof KnowledgeFileFileIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/dept/$deptId': {
      id: '/knowledge/dept/$deptId'
      path: '/dept/$deptId'
      fullPath: '/knowledge/dept/$deptId'
      preLoaderRoute: typeof KnowledgeDeptDeptIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/exam-admin/paper/new': {
      id: '/exam-admin/paper/new'
      path: '/paper/new'
      fullPath: '/exam-admin/paper/new'
      preLoaderRoute: typeof ExamAdminPaperNewRouteImport
      parentRoute: typeof ExamAdminRoute
    }
    '/assets/collection/$id': {
      id: '/assets/collection/$id'
      path: '/collection/$id'
      fullPath: '/assets/collection/$id'
      preLoaderRoute: typeof AssetsCollectionIdRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/scenario/typical/result/$id': {
      id: '/scenario/typical/result/$id'
      path: '/scenario/typical/result/$id'
      fullPath: '/scenario/typical/result/$id'
      preLoaderRoute: typeof ScenarioTypicalResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/sootblow/result/$id': {
      id: '/scenario/sootblow/result/$id'
      path: '/scenario/sootblow/result/$id'
      fullPath: '/scenario/sootblow/result/$id'
      preLoaderRoute: typeof ScenarioSootblowResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/peak/result/$id': {
      id: '/scenario/peak/result/$id'
      path: '/result/$id'
      fullPath: '/scenario/peak/result/$id'
      preLoaderRoute: typeof ScenarioPeakResultIdRouteImport
      parentRoute: typeof ScenarioPeakRoute
    }
    '/scenario/fault/result/$id': {
      id: '/scenario/fault/result/$id'
      path: '/result/$id'
      fullPath: '/scenario/fault/result/$id'
      preLoaderRoute: typeof ScenarioFaultResultIdRouteImport
      parentRoute: typeof ScenarioFaultRoute
    }
    '/learn-admin/topic/$topicId/edit': {
      id: '/learn-admin/topic/$topicId/edit'
      path: '/topic/$topicId/edit'
      fullPath: '/learn-admin/topic/$topicId/edit'
      preLoaderRoute: typeof LearnAdminTopicTopicIdEditRouteImport
      parentRoute: typeof LearnAdminRoute
    }
    '/knowledge/space/department/$departmentId': {
      id: '/knowledge/space/department/$departmentId'
      path: '/space/department/$departmentId'
      fullPath: '/knowledge/space/department/$departmentId'
      preLoaderRoute: typeof KnowledgeSpaceDepartmentDepartmentIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/exam-admin/paper/$paperId/preview': {
      id: '/exam-admin/paper/$paperId/preview'
      path: '/paper/$paperId/preview'
      fullPath: '/exam-admin/paper/$paperId/preview'
      preLoaderRoute: typeof ExamAdminPaperPaperIdPreviewRouteImport
      parentRoute: typeof ExamAdminRoute
    }
    '/exam-admin/paper/$paperId/edit': {
      id: '/exam-admin/paper/$paperId/edit'
      path: '/paper/$paperId/edit'
      fullPath: '/exam-admin/paper/$paperId/edit'
      preLoaderRoute: typeof ExamAdminPaperPaperIdEditRouteImport
      parentRoute: typeof ExamAdminRoute
    }
    '/knowledge/kb/$kbId/file/$fileId': {
      id: '/knowledge/kb/$kbId/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/knowledge/kb/$kbId/file/$fileId'
      preLoaderRoute: typeof KnowledgeKbKbIdFileFileIdRouteImport
      parentRoute: typeof KnowledgeKbKbIdRoute
    }
    '/knowledge/kb/$kbId/dir/$dirId': {
      id: '/knowledge/kb/$kbId/dir/$dirId'
      path: '/dir/$dirId'
      fullPath: '/knowledge/kb/$kbId/dir/$dirId'
      preLoaderRoute: typeof KnowledgeKbKbIdDirDirIdRouteImport
      parentRoute: typeof KnowledgeKbKbIdRoute
    }
    '/exam-admin/paper/$paperId/person/$personId': {
      id: '/exam-admin/paper/$paperId/person/$personId'
      path: '/paper/$paperId/person/$personId'
      fullPath: '/exam-admin/paper/$paperId/person/$personId'
      preLoaderRoute: typeof ExamAdminPaperPaperIdPersonPersonIdRouteImport
      parentRoute: typeof ExamAdminRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsCollectionIdRoute: typeof AssetsCollectionIdRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsCollectionIdRoute: AssetsCollectionIdRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface ExamAdminRouteChildren {
  ExamAdminIndexRoute: typeof ExamAdminIndexRoute
  ExamAdminPaperNewRoute: typeof ExamAdminPaperNewRoute
  ExamAdminPaperPaperIdEditRoute: typeof ExamAdminPaperPaperIdEditRoute
  ExamAdminPaperPaperIdPreviewRoute: typeof ExamAdminPaperPaperIdPreviewRoute
  ExamAdminPaperPaperIdPersonPersonIdRoute: typeof ExamAdminPaperPaperIdPersonPersonIdRoute
}

const ExamAdminRouteChildren: ExamAdminRouteChildren = {
  ExamAdminIndexRoute: ExamAdminIndexRoute,
  ExamAdminPaperNewRoute: ExamAdminPaperNewRoute,
  ExamAdminPaperPaperIdEditRoute: ExamAdminPaperPaperIdEditRoute,
  ExamAdminPaperPaperIdPreviewRoute: ExamAdminPaperPaperIdPreviewRoute,
  ExamAdminPaperPaperIdPersonPersonIdRoute:
    ExamAdminPaperPaperIdPersonPersonIdRoute,
}

const ExamAdminRouteWithChildren = ExamAdminRoute._addFileChildren(
  ExamAdminRouteChildren,
)

interface KnowledgeKbKbIdRouteChildren {
  KnowledgeKbKbIdDirDirIdRoute: typeof KnowledgeKbKbIdDirDirIdRoute
  KnowledgeKbKbIdFileFileIdRoute: typeof KnowledgeKbKbIdFileFileIdRoute
}

const KnowledgeKbKbIdRouteChildren: KnowledgeKbKbIdRouteChildren = {
  KnowledgeKbKbIdDirDirIdRoute: KnowledgeKbKbIdDirDirIdRoute,
  KnowledgeKbKbIdFileFileIdRoute: KnowledgeKbKbIdFileFileIdRoute,
}

const KnowledgeKbKbIdRouteWithChildren = KnowledgeKbKbIdRoute._addFileChildren(
  KnowledgeKbKbIdRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgeAdminRoute: typeof KnowledgeAdminRoute
  KnowledgeAllRoute: typeof KnowledgeAllRoute
  KnowledgeMineRoute: typeof KnowledgeMineRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  KnowledgeDeptDeptIdRoute: typeof KnowledgeDeptDeptIdRoute
  KnowledgeFileFileIdRoute: typeof KnowledgeFileFileIdRoute
  KnowledgeKbKbIdRoute: typeof KnowledgeKbKbIdRouteWithChildren
  KnowledgeLibLibIdRoute: typeof KnowledgeLibLibIdRoute
  KnowledgeSpacePublicRoute: typeof KnowledgeSpacePublicRoute
  KnowledgeSpaceDepartmentDepartmentIdRoute: typeof KnowledgeSpaceDepartmentDepartmentIdRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeAdminRoute: KnowledgeAdminRoute,
  KnowledgeAllRoute: KnowledgeAllRoute,
  KnowledgeMineRoute: KnowledgeMineRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  KnowledgeDeptDeptIdRoute: KnowledgeDeptDeptIdRoute,
  KnowledgeFileFileIdRoute: KnowledgeFileFileIdRoute,
  KnowledgeKbKbIdRoute: KnowledgeKbKbIdRouteWithChildren,
  KnowledgeLibLibIdRoute: KnowledgeLibLibIdRoute,
  KnowledgeSpacePublicRoute: KnowledgeSpacePublicRoute,
  KnowledgeSpaceDepartmentDepartmentIdRoute:
    KnowledgeSpaceDepartmentDepartmentIdRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface LearnAdminRouteChildren {
  LearnAdminIndexRoute: typeof LearnAdminIndexRoute
  LearnAdminTopicNewRoute: typeof LearnAdminTopicNewRoute
  LearnAdminTopicTopicIdEditRoute: typeof LearnAdminTopicTopicIdEditRoute
}

const LearnAdminRouteChildren: LearnAdminRouteChildren = {
  LearnAdminIndexRoute: LearnAdminIndexRoute,
  LearnAdminTopicNewRoute: LearnAdminTopicNewRoute,
  LearnAdminTopicTopicIdEditRoute: LearnAdminTopicTopicIdEditRoute,
}

const LearnAdminRouteWithChildren = LearnAdminRoute._addFileChildren(
  LearnAdminRouteChildren,
)

interface ScenarioFaultRouteChildren {
  ScenarioFaultIndexRoute: typeof ScenarioFaultIndexRoute
  ScenarioFaultResultIdRoute: typeof ScenarioFaultResultIdRoute
}

const ScenarioFaultRouteChildren: ScenarioFaultRouteChildren = {
  ScenarioFaultIndexRoute: ScenarioFaultIndexRoute,
  ScenarioFaultResultIdRoute: ScenarioFaultResultIdRoute,
}

const ScenarioFaultRouteWithChildren = ScenarioFaultRoute._addFileChildren(
  ScenarioFaultRouteChildren,
)

interface ScenarioPeakRouteChildren {
  ScenarioPeakResultIdRoute: typeof ScenarioPeakResultIdRoute
}

const ScenarioPeakRouteChildren: ScenarioPeakRouteChildren = {
  ScenarioPeakResultIdRoute: ScenarioPeakResultIdRoute,
}

const ScenarioPeakRouteWithChildren = ScenarioPeakRoute._addFileChildren(
  ScenarioPeakRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  ChatRoute: ChatRoute,
  ExamAdminRoute: ExamAdminRouteWithChildren,
  GovernanceRoute: GovernanceRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LearnAdminRoute: LearnAdminRouteWithChildren,
  QuestionBankRoute: QuestionBankRoute,
  SceneRoute: SceneRoute,
  SearchRoute: SearchRoute,
  ScenarioFaultRoute: ScenarioFaultRouteWithChildren,
  ScenarioPeakRoute: ScenarioPeakRouteWithChildren,
  TrainingExamRoute: TrainingExamRoute,
  TrainingGrowthRoute: TrainingGrowthRoute,
  TrainingPracticeRoute: TrainingPracticeRoute,
  TrainingRecordsRoute: TrainingRecordsRoute,
  TrainingWrongRoute: TrainingWrongRoute,
  LearnIndexRoute: LearnIndexRoute,
  ScenarioIndexRoute: ScenarioIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  LearnDocIdRoute: LearnDocIdRoute,
  LearnTopicIdRoute: LearnTopicIdRoute,
  TrainingResultIdRoute: TrainingResultIdRoute,
  TrainingSessionIdRoute: TrainingSessionIdRoute,
  ScenarioTypicalIndexRoute: ScenarioTypicalIndexRoute,
  ScenarioSootblowResultIdRoute: ScenarioSootblowResultIdRoute,
  ScenarioTypicalResultIdRoute: ScenarioTypicalResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
