/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SceneRouteImport } from './routes/scene'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ExamAdminRouteImport } from './routes/exam-admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as ScenarioIndexRouteImport } from './routes/scenario.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as TrainingWrongRouteImport } from './routes/training.wrong'
import { Route as TrainingPracticeRouteImport } from './routes/training.practice'
import { Route as TrainingGrowthRouteImport } from './routes/training.growth'
import { Route as TrainingExamRouteImport } from './routes/training.exam'
import { Route as ScenarioPeakRouteImport } from './routes/scenario.peak'
import { Route as ScenarioFaultRouteImport } from './routes/scenario.fault'
import { Route as ScenarioTypicalIndexRouteImport } from './routes/scenario.typical.index'
import { Route as TrainingSessionIdRouteImport } from './routes/training.session.$id'
import { Route as TrainingResultIdRouteImport } from './routes/training.result.$id'
import { Route as LearnTopicIdRouteImport } from './routes/learn.topic.$id'
import { Route as LearnDocIdRouteImport } from './routes/learn.doc.$id'
import { Route as AssetsCollectionIdRouteImport } from './routes/assets.collection.$id'
import { Route as ScenarioTypicalResultIdRouteImport } from './routes/scenario.typical.result.$id'
import { Route as ScenarioSootblowResultIdRouteImport } from './routes/scenario.sootblow.result.$id'
import { Route as ScenarioPeakResultIdRouteImport } from './routes/scenario.peak.result.$id'
import { Route as ScenarioFaultResultIdRouteImport } from './routes/scenario.fault.result.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneRoute = SceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamAdminRoute = ExamAdminRouteImport.update({
  id: '/exam-admin',
  path: '/exam-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioIndexRoute = ScenarioIndexRouteImport.update({
  id: '/scenario/',
  path: '/scenario/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingWrongRoute = TrainingWrongRouteImport.update({
  id: '/training/wrong',
  path: '/training/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingPracticeRoute = TrainingPracticeRouteImport.update({
  id: '/training/practice',
  path: '/training/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingGrowthRoute = TrainingGrowthRouteImport.update({
  id: '/training/growth',
  path: '/training/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingExamRoute = TrainingExamRouteImport.update({
  id: '/training/exam',
  path: '/training/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioPeakRoute = ScenarioPeakRouteImport.update({
  id: '/scenario/peak',
  path: '/scenario/peak',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioFaultRoute = ScenarioFaultRouteImport.update({
  id: '/scenario/fault',
  path: '/scenario/fault',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioTypicalIndexRoute = ScenarioTypicalIndexRouteImport.update({
  id: '/scenario/typical/',
  path: '/scenario/typical/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingSessionIdRoute = TrainingSessionIdRouteImport.update({
  id: '/training/session/$id',
  path: '/training/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingResultIdRoute = TrainingResultIdRouteImport.update({
  id: '/training/result/$id',
  path: '/training/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicIdRoute = LearnTopicIdRouteImport.update({
  id: '/learn/topic/$id',
  path: '/learn/topic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDocIdRoute = LearnDocIdRouteImport.update({
  id: '/learn/doc/$id',
  path: '/learn/doc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsCollectionIdRoute = AssetsCollectionIdRouteImport.update({
  id: '/collection/$id',
  path: '/collection/$id',
  getParentRoute: () => AssetsRoute,
} as any)
const ScenarioTypicalResultIdRoute = ScenarioTypicalResultIdRouteImport.update({
  id: '/scenario/typical/result/$id',
  path: '/scenario/typical/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioSootblowResultIdRoute =
  ScenarioSootblowResultIdRouteImport.update({
    id: '/scenario/sootblow/result/$id',
    path: '/scenario/sootblow/result/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScenarioPeakResultIdRoute = ScenarioPeakResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => ScenarioPeakRoute,
} as any)
const ScenarioFaultResultIdRoute = ScenarioFaultResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => ScenarioFaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/chat': typeof ChatRoute
  '/exam-admin': typeof ExamAdminRoute
  '/governance': typeof GovernanceRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/scenario/fault': typeof ScenarioFaultRouteWithChildren
  '/scenario/peak': typeof ScenarioPeakRouteWithChildren
  '/training/exam': typeof TrainingExamRoute
  '/training/growth': typeof TrainingGrowthRoute
  '/training/practice': typeof TrainingPracticeRoute
  '/training/wrong': typeof TrainingWrongRoute
  '/learn/': typeof LearnIndexRoute
  '/scenario/': typeof ScenarioIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/assets/collection/$id': typeof AssetsCollectionIdRoute
  '/learn/doc/$id': typeof LearnDocIdRoute
  '/learn/topic/$id': typeof LearnTopicIdRoute
  '/training/result/$id': typeof TrainingResultIdRoute
  '/training/session/$id': typeof TrainingSessionIdRoute
  '/scenario/typical/': typeof ScenarioTypicalIndexRoute
  '/scenario/fault/result/$id': typeof ScenarioFaultResultIdRoute
  '/scenario/peak/result/$id': typeof ScenarioPeakResultIdRoute
  '/scenario/sootblow/result/$id': typeof ScenarioSootblowResultIdRoute
  '/scenario/typical/result/$id': typeof ScenarioTypicalResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/chat': typeof ChatRoute
  '/exam-admin': typeof ExamAdminRoute
  '/governance': typeof GovernanceRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/scenario/fault': typeof ScenarioFaultRouteWithChildren
  '/scenario/peak': typeof ScenarioPeakRouteWithChildren
  '/training/exam': typeof TrainingExamRoute
  '/training/growth': typeof TrainingGrowthRoute
  '/training/practice': typeof TrainingPracticeRoute
  '/training/wrong': typeof TrainingWrongRoute
  '/learn': typeof LearnIndexRoute
  '/scenario': typeof ScenarioIndexRoute
  '/training': typeof TrainingIndexRoute
  '/assets/collection/$id': typeof AssetsCollectionIdRoute
  '/learn/doc/$id': typeof LearnDocIdRoute
  '/learn/topic/$id': typeof LearnTopicIdRoute
  '/training/result/$id': typeof TrainingResultIdRoute
  '/training/session/$id': typeof TrainingSessionIdRoute
  '/scenario/typical': typeof ScenarioTypicalIndexRoute
  '/scenario/fault/result/$id': typeof ScenarioFaultResultIdRoute
  '/scenario/peak/result/$id': typeof ScenarioPeakResultIdRoute
  '/scenario/sootblow/result/$id': typeof ScenarioSootblowResultIdRoute
  '/scenario/typical/result/$id': typeof ScenarioTypicalResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/chat': typeof ChatRoute
  '/exam-admin': typeof ExamAdminRoute
  '/governance': typeof GovernanceRoute
  '/scene': typeof SceneRoute
  '/search': typeof SearchRoute
  '/scenario/fault': typeof ScenarioFaultRouteWithChildren
  '/scenario/peak': typeof ScenarioPeakRouteWithChildren
  '/training/exam': typeof TrainingExamRoute
  '/training/growth': typeof TrainingGrowthRoute
  '/training/practice': typeof TrainingPracticeRoute
  '/training/wrong': typeof TrainingWrongRoute
  '/learn/': typeof LearnIndexRoute
  '/scenario/': typeof ScenarioIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/assets/collection/$id': typeof AssetsCollectionIdRoute
  '/learn/doc/$id': typeof LearnDocIdRoute
  '/learn/topic/$id': typeof LearnTopicIdRoute
  '/training/result/$id': typeof TrainingResultIdRoute
  '/training/session/$id': typeof TrainingSessionIdRoute
  '/scenario/typical/': typeof ScenarioTypicalIndexRoute
  '/scenario/fault/result/$id': typeof ScenarioFaultResultIdRoute
  '/scenario/peak/result/$id': typeof ScenarioPeakResultIdRoute
  '/scenario/sootblow/result/$id': typeof ScenarioSootblowResultIdRoute
  '/scenario/typical/result/$id': typeof ScenarioTypicalResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/chat'
    | '/exam-admin'
    | '/governance'
    | '/scene'
    | '/search'
    | '/scenario/fault'
    | '/scenario/peak'
    | '/training/exam'
    | '/training/growth'
    | '/training/practice'
    | '/training/wrong'
    | '/learn/'
    | '/scenario/'
    | '/training/'
    | '/assets/collection/$id'
    | '/learn/doc/$id'
    | '/learn/topic/$id'
    | '/training/result/$id'
    | '/training/session/$id'
    | '/scenario/typical/'
    | '/scenario/fault/result/$id'
    | '/scenario/peak/result/$id'
    | '/scenario/sootblow/result/$id'
    | '/scenario/typical/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/chat'
    | '/exam-admin'
    | '/governance'
    | '/scene'
    | '/search'
    | '/scenario/fault'
    | '/scenario/peak'
    | '/training/exam'
    | '/training/growth'
    | '/training/practice'
    | '/training/wrong'
    | '/learn'
    | '/scenario'
    | '/training'
    | '/assets/collection/$id'
    | '/learn/doc/$id'
    | '/learn/topic/$id'
    | '/training/result/$id'
    | '/training/session/$id'
    | '/scenario/typical'
    | '/scenario/fault/result/$id'
    | '/scenario/peak/result/$id'
    | '/scenario/sootblow/result/$id'
    | '/scenario/typical/result/$id'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/chat'
    | '/exam-admin'
    | '/governance'
    | '/scene'
    | '/search'
    | '/scenario/fault'
    | '/scenario/peak'
    | '/training/exam'
    | '/training/growth'
    | '/training/practice'
    | '/training/wrong'
    | '/learn/'
    | '/scenario/'
    | '/training/'
    | '/assets/collection/$id'
    | '/learn/doc/$id'
    | '/learn/topic/$id'
    | '/training/result/$id'
    | '/training/session/$id'
    | '/scenario/typical/'
    | '/scenario/fault/result/$id'
    | '/scenario/peak/result/$id'
    | '/scenario/sootblow/result/$id'
    | '/scenario/typical/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  ChatRoute: typeof ChatRoute
  ExamAdminRoute: typeof ExamAdminRoute
  GovernanceRoute: typeof GovernanceRoute
  SceneRoute: typeof SceneRoute
  SearchRoute: typeof SearchRoute
  ScenarioFaultRoute: typeof ScenarioFaultRouteWithChildren
  ScenarioPeakRoute: typeof ScenarioPeakRouteWithChildren
  TrainingExamRoute: typeof TrainingExamRoute
  TrainingGrowthRoute: typeof TrainingGrowthRoute
  TrainingPracticeRoute: typeof TrainingPracticeRoute
  TrainingWrongRoute: typeof TrainingWrongRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ScenarioIndexRoute: typeof ScenarioIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  LearnDocIdRoute: typeof LearnDocIdRoute
  LearnTopicIdRoute: typeof LearnTopicIdRoute
  TrainingResultIdRoute: typeof TrainingResultIdRoute
  TrainingSessionIdRoute: typeof TrainingSessionIdRoute
  ScenarioTypicalIndexRoute: typeof ScenarioTypicalIndexRoute
  ScenarioSootblowResultIdRoute: typeof ScenarioSootblowResultIdRoute
  ScenarioTypicalResultIdRoute: typeof ScenarioTypicalResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-admin': {
      id: '/exam-admin'
      path: '/exam-admin'
      fullPath: '/exam-admin'
      preLoaderRoute: typeof ExamAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/': {
      id: '/scenario/'
      path: '/scenario'
      fullPath: '/scenario/'
      preLoaderRoute: typeof ScenarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/wrong': {
      id: '/training/wrong'
      path: '/training/wrong'
      fullPath: '/training/wrong'
      preLoaderRoute: typeof TrainingWrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/practice': {
      id: '/training/practice'
      path: '/training/practice'
      fullPath: '/training/practice'
      preLoaderRoute: typeof TrainingPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/growth': {
      id: '/training/growth'
      path: '/training/growth'
      fullPath: '/training/growth'
      preLoaderRoute: typeof TrainingGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/exam': {
      id: '/training/exam'
      path: '/training/exam'
      fullPath: '/training/exam'
      preLoaderRoute: typeof TrainingExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/peak': {
      id: '/scenario/peak'
      path: '/scenario/peak'
      fullPath: '/scenario/peak'
      preLoaderRoute: typeof ScenarioPeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/fault': {
      id: '/scenario/fault'
      path: '/scenario/fault'
      fullPath: '/scenario/fault'
      preLoaderRoute: typeof ScenarioFaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/typical/': {
      id: '/scenario/typical/'
      path: '/scenario/typical'
      fullPath: '/scenario/typical/'
      preLoaderRoute: typeof ScenarioTypicalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/session/$id': {
      id: '/training/session/$id'
      path: '/training/session/$id'
      fullPath: '/training/session/$id'
      preLoaderRoute: typeof TrainingSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/result/$id': {
      id: '/training/result/$id'
      path: '/training/result/$id'
      fullPath: '/training/result/$id'
      preLoaderRoute: typeof TrainingResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/topic/$id': {
      id: '/learn/topic/$id'
      path: '/learn/topic/$id'
      fullPath: '/learn/topic/$id'
      preLoaderRoute: typeof LearnTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/doc/$id': {
      id: '/learn/doc/$id'
      path: '/learn/doc/$id'
      fullPath: '/learn/doc/$id'
      preLoaderRoute: typeof LearnDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/collection/$id': {
      id: '/assets/collection/$id'
      path: '/collection/$id'
      fullPath: '/assets/collection/$id'
      preLoaderRoute: typeof AssetsCollectionIdRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/scenario/typical/result/$id': {
      id: '/scenario/typical/result/$id'
      path: '/scenario/typical/result/$id'
      fullPath: '/scenario/typical/result/$id'
      preLoaderRoute: typeof ScenarioTypicalResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/sootblow/result/$id': {
      id: '/scenario/sootblow/result/$id'
      path: '/scenario/sootblow/result/$id'
      fullPath: '/scenario/sootblow/result/$id'
      preLoaderRoute: typeof ScenarioSootblowResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario/peak/result/$id': {
      id: '/scenario/peak/result/$id'
      path: '/result/$id'
      fullPath: '/scenario/peak/result/$id'
      preLoaderRoute: typeof ScenarioPeakResultIdRouteImport
      parentRoute: typeof ScenarioPeakRoute
    }
    '/scenario/fault/result/$id': {
      id: '/scenario/fault/result/$id'
      path: '/result/$id'
      fullPath: '/scenario/fault/result/$id'
      preLoaderRoute: typeof ScenarioFaultResultIdRouteImport
      parentRoute: typeof ScenarioFaultRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsCollectionIdRoute: typeof AssetsCollectionIdRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsCollectionIdRoute: AssetsCollectionIdRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface ScenarioFaultRouteChildren {
  ScenarioFaultResultIdRoute: typeof ScenarioFaultResultIdRoute
}

const ScenarioFaultRouteChildren: ScenarioFaultRouteChildren = {
  ScenarioFaultResultIdRoute: ScenarioFaultResultIdRoute,
}

const ScenarioFaultRouteWithChildren = ScenarioFaultRoute._addFileChildren(
  ScenarioFaultRouteChildren,
)

interface ScenarioPeakRouteChildren {
  ScenarioPeakResultIdRoute: typeof ScenarioPeakResultIdRoute
}

const ScenarioPeakRouteChildren: ScenarioPeakRouteChildren = {
  ScenarioPeakResultIdRoute: ScenarioPeakResultIdRoute,
}

const ScenarioPeakRouteWithChildren = ScenarioPeakRoute._addFileChildren(
  ScenarioPeakRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  ChatRoute: ChatRoute,
  ExamAdminRoute: ExamAdminRoute,
  GovernanceRoute: GovernanceRoute,
  SceneRoute: SceneRoute,
  SearchRoute: SearchRoute,
  ScenarioFaultRoute: ScenarioFaultRouteWithChildren,
  ScenarioPeakRoute: ScenarioPeakRouteWithChildren,
  TrainingExamRoute: TrainingExamRoute,
  TrainingGrowthRoute: TrainingGrowthRoute,
  TrainingPracticeRoute: TrainingPracticeRoute,
  TrainingWrongRoute: TrainingWrongRoute,
  LearnIndexRoute: LearnIndexRoute,
  ScenarioIndexRoute: ScenarioIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  LearnDocIdRoute: LearnDocIdRoute,
  LearnTopicIdRoute: LearnTopicIdRoute,
  TrainingResultIdRoute: TrainingResultIdRoute,
  TrainingSessionIdRoute: TrainingSessionIdRoute,
  ScenarioTypicalIndexRoute: ScenarioTypicalIndexRoute,
  ScenarioSootblowResultIdRoute: ScenarioSootblowResultIdRoute,
  ScenarioTypicalResultIdRoute: ScenarioTypicalResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
